from __future__ import annotations


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    ai_decision_interval_base = _int(constants, "ai_decision_interval_base", 30)
    ai_aggression_default = _float(constants, "ai_aggression_default", 0.6)
    global_rules = " ".join(str(rule).lower() for rule in getattr(hlr, "global_rules", []) or [])
    disable_specials = "true" if "no special moves" in global_rules else "false"
    return f"""extends Node
## ai_system - generated by 2d_fighter template python
## Reads:  fighter.ai_decision_timer, fighter.ai_current_plan, fighter.ai_decision_interval, fighter.ai_aggression, fighter.position, fighter.rage_stacks, fighter.is_cpu, fighter.player_slot, game.round_state
## Writes: fighter.ai_decision_timer, fighter.ai_current_plan, fighter.ai_decision_interval, fighter.ai_aggression

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}

@export var ai_decision_interval_base: int = {ai_decision_interval_base}
@export var ai_aggression_default: float = {ai_aggression_default}
@export var disable_special_moves: bool = {disable_specials}
@export var test_mode: String = ""

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("ai_decision_interval_base"):
        ai_decision_interval_base = config["ai_decision_interval_base"] as int
    if config.has("ai_aggression_default"):
        ai_aggression_default = config["ai_aggression_default"] as float
    if config.has("disable_special_moves"):
        disable_special_moves = bool(config["disable_special_moves"])
    if config.has("test_mode"):
        test_mode = str(config["test_mode"])

    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        if _is_cpu_fighter(fighter):
            fighter.ai_decision_interval = ai_decision_interval_base
            fighter.ai_aggression = ai_aggression_default
            fighter.ai_decision_timer = 0
            fighter.ai_current_plan = "idle"
        else:
            fighter.ai_current_plan = "idle"

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    if fighters.size() < 2:
        return
    var round_state := _current_round_state()

    for fighter in fighters:
        if fighter == null or not _is_cpu_fighter(fighter):
            continue
        if round_state != "fighting":
            fighter.ai_decision_timer = 0
            if str(fighter.ai_current_plan) != "idle":
                fighter.ai_current_plan = "idle"
                print("[trace] ai.plan_reset fighter=%s reason=round_state state=%s" % [fighter.name, round_state])
            continue

        var opponent = _pick_opponent(fighter, fighters)
        if opponent == null:
            continue

        var forced_plan := _test_mode_plan(fighter, opponent)
        if forced_plan != "":
            if str(fighter.ai_current_plan) != forced_plan:
                print("[trace] ai.test_mode fighter=%s mode=%s plan=%s" % [fighter.name, test_mode, forced_plan])
            fighter.ai_current_plan = forced_plan
            fighter.ai_decision_timer = 0
            continue

        if int(fighter.ai_decision_timer) > 0:
            fighter.ai_decision_timer = max(int(fighter.ai_decision_timer) - 1, 0)
        if int(fighter.ai_decision_timer) == 0:
            _evaluate_and_select_plan(fighter, opponent)

func _is_cpu_fighter(fighter) -> bool:
    if fighter == null:
        return false
    if fighter.get("is_cpu") != null:
        return bool(fighter.is_cpu)
    return int(fighter.get("player_slot") if fighter.get("player_slot") != null else 0) > 0

func _pick_opponent(fighter, fighters: Array):
    for candidate in fighters:
        if candidate != fighter:
            return candidate
    return null

func _test_mode_plan(fighter, opponent) -> String:
    match test_mode:
        "dummy":
            return "idle"
        "rage_ready":
            return "idle"
        "projectile_ready":
            return "idle"
        "uppercut_ready":
            return "idle"
        "guard_high":
            return "block"
        "guard_low":
            return "block"
        "aggressor":
            var distance := float(fighter.position.distance_to(opponent.position))
            return "attack_close" if distance < 130.0 else "approach"
        _:
            return ""

func _current_round_state() -> String:
    var parent = get_parent()
    if parent != null:
        var scene_state = parent.get("round_state")
        if scene_state != null:
            return str(scene_state)
    if sibling_systems.has("round_system"):
        var round_state = sibling_systems["round_system"].get("round_state")
        if round_state != null:
            return str(round_state)
    return "fighting"

func _evaluate_and_select_plan(fighter, opponent) -> void:
    var distance := float(fighter.position.distance_to(opponent.position))
    var aggression := float(fighter.ai_aggression)
    var rage := int(fighter.rage_stacks)
    var rand_val := randf()
    var new_plan := "idle"

    if distance < 105.0:
        if rand_val < aggression * 0.75:
            new_plan = "attack_close"
        elif rand_val < aggression * 0.75 + 0.2:
            new_plan = "block"
        else:
            new_plan = "retreat"
    elif distance > 260.0:
        if rand_val < 0.55:
            new_plan = "approach"
        elif not disable_special_moves and rand_val < 0.75:
            new_plan = "attack_far"
        elif rand_val < 0.9:
            new_plan = "jump"
        else:
            new_plan = "idle"
    else:
        if rand_val < 0.35:
            new_plan = "approach"
        elif rand_val < 0.65:
            new_plan = "attack_close"
        elif rand_val < 0.82:
            new_plan = "block"
        elif not disable_special_moves and rand_val < 0.9:
            new_plan = "attack_far"
        else:
            new_plan = "jump"

    if rage > 0 and disable_special_moves and new_plan == "idle":
        new_plan = "approach"

    var old_plan := str(fighter.ai_current_plan)
    fighter.ai_current_plan = new_plan
    fighter.ai_decision_timer = max(ai_decision_interval_base + randi_range(-5, 5), 1)
    print("[trace] ai.decision fighter=%s plan=%s old_plan=%s distance=%.1f aggression=%.2f rage=%d timer=%d disable_specials=%s" % [
        fighter.name,
        new_plan,
        old_plan,
        distance,
        aggression,
        rage,
        fighter.ai_decision_timer,
        disable_special_moves,
    ])
"""
