from __future__ import annotations


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    rage_glow_decay_rate = _float(constants, "rage_glow_decay_rate", 0.05)
    return f"""extends Node
## animation_system - generated by 2d_fighter template python
## Reads:  fighter.current_action, fighter.action_frame, fighter.current_animation, fighter.animation_frame, fighter.hitstop_timer, fighter.facing_direction, fighter.is_powered_special, fighter.sprite_flip_h
## Writes: fighter.current_animation, fighter.animation_frame, fighter.sprite_flip_h, fighter.rage_glow_intensity, fighter.sprite_flash_color

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _texture_cache: Dictionary = {{}}
var _texture_sequence_cache: Dictionary = {{}}
var _fighter_prefix_cache: Dictionary = {{}}

@export var rage_glow_decay_rate: float = {rage_glow_decay_rate}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("rage_glow_decay_rate"):
        rage_glow_decay_rate = config["rage_glow_decay_rate"] as float
    _texture_cache.clear()
    _texture_sequence_cache.clear()
    _fighter_prefix_cache.clear()

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        _process_fighter(fighter)

func _process_fighter(fighter) -> void:
    var action := str(fighter.current_action)
    var prev_anim := str(fighter.current_animation)
    var next_anim := _action_to_animation_label(fighter, action)
    fighter.current_animation = next_anim
    if next_anim != prev_anim:
        fighter.animation_frame = 0
        print("[trace] anim.swap fighter=%s from=%s to=%s" % [fighter.name, prev_anim, next_anim])
    elif int(fighter.hitstop_timer) <= 0:
        fighter.animation_frame = int(fighter.animation_frame) + 1

    fighter.sprite_flip_h = int(fighter.facing_direction) < 0
    if bool(fighter.is_powered_special):
        fighter.rage_glow_intensity = 1.0
    else:
        fighter.rage_glow_intensity = maxf(float(fighter.rage_glow_intensity) - rage_glow_decay_rate, 0.0)
    fighter.sprite_flash_color = _flash_color_for_action(action)

    var sprite = fighter.get_node_or_null("Sprite")
    if sprite is Sprite2D:
        _apply_sprite_visuals(fighter, sprite as Sprite2D, next_anim)

func _fighter_prefix(fighter) -> String:
    var key := str(fighter.name)
    if _fighter_prefix_cache.has(key):
        return str(_fighter_prefix_cache[key])
    var prefix := "fighter"
    var override_prefix := str(fighter.get("visual_asset_prefix") if fighter.get("visual_asset_prefix") != null else "").strip_edges()
    if override_prefix != "":
        prefix = override_prefix
    else:
        var script = fighter.get_script()
        if script != null:
            var resource_path := str(script.resource_path)
            if resource_path != "":
                prefix = resource_path.get_file().get_basename()
    _fighter_prefix_cache[key] = prefix
    return prefix

func _animation_candidates_for_action(fighter, action: String) -> Array[String]:
    var prefix := _fighter_prefix(fighter)
    match action:
        "idle", "intro", "victory":
            return [prefix + "_idle", "idle"]
        "walk_forward", "walk_back":
            return [prefix + "_walk", prefix + "_idle"]
        "crouch":
            return [prefix + "_crouch", prefix + "_idle"]
        "jump_neutral", "jump_forward", "jump_back":
            return [prefix + "_jump", prefix + "_idle"]
        "light_punch", "crouch_light_punch", "jump_light_punch":
            return [prefix + "_light_punch", prefix + "_heavy_punch", prefix + "_idle"]
        "medium_punch", "crouch_medium_punch", "jump_medium_punch":
            return [prefix + "_heavy_punch", prefix + "_light_punch", prefix + "_idle"]
        "heavy_punch", "crouch_heavy_punch", "jump_heavy_punch", "throw":
            return [prefix + "_heavy_punch", prefix + "_light_punch", prefix + "_idle"]
        "light_kick", "crouch_light_kick", "jump_light_kick":
            return [prefix + "_light_kick", prefix + "_heavy_kick", prefix + "_idle"]
        "medium_kick", "crouch_medium_kick", "jump_medium_kick":
            return [prefix + "_heavy_kick", prefix + "_light_kick", prefix + "_idle"]
        "heavy_kick", "crouch_heavy_kick", "jump_heavy_kick":
            return [prefix + "_heavy_kick", prefix + "_light_kick", prefix + "_idle"]
        "block_high", "block_low":
            return [prefix + "_block", prefix + "_crouch", prefix + "_idle"]
        "hit_high", "hit_low", "hit_airborne":
            return [prefix + "_hit", prefix + "_dizzy", prefix + "_idle"]
        "stunned":
            return [str(fighter.get("stun_animation")), prefix + "_dizzy", prefix + "_hit", prefix + "_idle"]
        "ko":
            return [prefix + "_ko", prefix + "_hit", prefix + "_idle"]
        "special_projectile":
            return [str(fighter.get("hadouken_animation")), prefix + "_hadouken", prefix + "_heavy_punch", prefix + "_idle"]
        "special_uppercut":
            return [str(fighter.get("shoryuken_animation")), prefix + "_shoryuken", prefix + "_jump", prefix + "_idle"]
        "special_spinning":
            return [str(fighter.get("tatsumaki_senpuukyaku_animation")), prefix + "_tatsumaki", prefix + "_heavy_kick", prefix + "_idle"]
        _:
            return [prefix + "_idle", "idle"]

func _action_to_animation_label(fighter, action: String) -> String:
    for label in _animation_candidates_for_action(fighter, action):
        if label == "":
            continue
        if _animation_available(fighter, label):
            return label
    return _fighter_prefix(fighter) + "_idle"

func _animation_available(fighter, label: String) -> bool:
    return _load_texture(fighter, label) != null or not _load_texture_sequence(fighter, label).is_empty()

func _candidate_asset_labels(fighter, label: String) -> Array[String]:
    var prefix := _fighter_prefix(fighter)
    var labels: Array[String] = [label]
    var prefix_token := prefix + "_"
    if label.begins_with(prefix_token):
        labels.append(label.substr(prefix_token.length()))
    return labels

func _load_direct_texture(prefix: String, label: String):
    var cache_key := "%s::%s" % [prefix, label]
    if _texture_cache.has(cache_key):
        return _texture_cache[cache_key]
    var candidates := [
        "res://assets/%s/%s.png" % [prefix, label],
        "res://assets/%s/%s.jpg" % [prefix, label],
    ]
    for path in candidates:
        if ResourceLoader.exists(path):
            var texture = load(path)
            _texture_cache[cache_key] = texture
            return texture
    _texture_cache[cache_key] = null
    return null

func _load_texture_sequence(fighter, label: String) -> Array:
    if label == "":
        return []
    if _texture_sequence_cache.has(label):
        return _texture_sequence_cache[label]
    var prefix := _fighter_prefix(fighter)
    var frames: Array = []
    for candidate_label in _candidate_asset_labels(fighter, label):
        var candidate_frames: Array = []
        for idx in range(24):
            var texture = _load_direct_texture(prefix, "%s_%d" % [candidate_label, idx])
            if texture == null:
                break
            candidate_frames.append(texture)
        if not candidate_frames.is_empty():
            frames = candidate_frames
            break
    _texture_sequence_cache[label] = frames
    return frames

func _load_texture(fighter, label: String):
    if label == "":
        return null
    var frame_sequence := _load_texture_sequence(fighter, label)
    if not frame_sequence.is_empty():
        return frame_sequence[0]
    var prefix := _fighter_prefix(fighter)
    for candidate_label in _candidate_asset_labels(fighter, label):
        var texture = _load_direct_texture(prefix, candidate_label)
        if texture != null:
            return texture
    return null

func _flash_color_for_action(action: String) -> Color:
    if action in ["hit_high", "hit_low", "hit_airborne", "stunned"]:
        return Color(1.0, 1.0, 1.0, 0.7)
    if action in ["block_high", "block_low"]:
        return Color(1.0, 0.95, 0.25, 0.65)
    return Color(0.0, 0.0, 0.0, 0.0)

func _apply_sprite_visuals(fighter, sprite: Sprite2D, anim_label: String) -> void:
    var texture = null
    var frame_sequence := _load_texture_sequence(fighter, anim_label)
    if not frame_sequence.is_empty():
        var frame_stride := 8
        if "walk" in anim_label:
            frame_stride = 6
        elif "hit" in anim_label or "block" in anim_label:
            frame_stride = 5
        var frame_index := int(floor(float(fighter.animation_frame) / float(max(frame_stride, 1)))) % frame_sequence.size()
        texture = frame_sequence[frame_index]
    else:
        texture = _load_texture(fighter, anim_label)
    if texture != null and sprite.texture != texture:
        sprite.texture = texture

    var texture_height := 0.0
    if sprite.texture != null:
        texture_height = float(sprite.texture.get_size().y)
    var desired_height := 260.0
    var height_percent = fighter.get("sprite_height_percent")
    if height_percent != null and float(height_percent) > 0.0:
        desired_height = maxf(get_viewport().get_visible_rect().size.y * float(height_percent), 180.0)

    var scale_hint := Vector2.ONE
    var raw_scale = fighter.get("sprite_scale")
    if raw_scale is Vector2:
        scale_hint = raw_scale as Vector2
    if texture_height > 0.0:
        var base_scale := desired_height / texture_height
        sprite.scale = Vector2(base_scale * maxf(absf(scale_hint.x), 0.01), base_scale * maxf(scale_hint.y, 0.01))
        sprite.position = Vector2(0.0, -(texture_height * sprite.scale.y) * 0.5)

    sprite.flip_h = bool(fighter.sprite_flip_h)

    var glow_strength := clampf(float(fighter.rage_glow_intensity), 0.0, 1.0)
    var glow_color := Color(1.0, 0.55, 0.2, 1.0)
    var flash_color: Color = fighter.sprite_flash_color if fighter.get("sprite_flash_color") is Color else Color(0.0, 0.0, 0.0, 0.0)
    var base_modulate := Color.WHITE.lerp(glow_color, glow_strength * 0.65)
    if flash_color.a > 0.0:
        var flash_mix := clampf(flash_color.a, 0.0, 1.0)
        base_modulate = base_modulate.lerp(Color(flash_color.r, flash_color.g, flash_color.b, 1.0), flash_mix)
    sprite.modulate = base_modulate
"""
