from __future__ import annotations


def emit_system(slice_data, hlr, spec, constants) -> str:
    return """extends Node
## blocking_system - generated by 2d_fighter template python
## Reads:  fighter.input_buffer, fighter.can_block, fighter.is_crouching, fighter.is_airborne, fighter.blockstun_timer, fighter.hitstun_timer, fighter.stun_timer, fighter.is_stunned, fighter.current_action
## Writes: fighter.is_blocking, fighter.block_type, fighter.blockstun_timer

var entity_pools: Dictionary = {}
var config: Dictionary = {}
var sibling_systems: Dictionary = {}
@export var test_mode: String = ""

func setup(pools: Dictionary, cfg: Dictionary = {}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("test_mode"):
        test_mode = str(config["test_mode"])

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        _process_fighter(fighter)

func _process_fighter(fighter) -> void:
    var was_blocking := bool(fighter.is_blocking)
    var prev_block_type := str(fighter.block_type)
    var blockstun: int = max(int(fighter.blockstun_timer), 0)
    var desired_block_type: String = _desired_block_type(fighter)

    if blockstun > 0:
        fighter.blockstun_timer = blockstun - 1
        fighter.is_blocking = true
        if desired_block_type == "none":
            desired_block_type = "crouch" if bool(fighter.is_crouching) else "stand"
        fighter.block_type = desired_block_type
    else:
        fighter.blockstun_timer = 0
        fighter.is_blocking = desired_block_type != "none"
        fighter.block_type = desired_block_type

    if fighter.is_blocking and (not was_blocking or prev_block_type != fighter.block_type):
        print("[trace] blocking.engaged fighter=%s block_type=%s" % [fighter.name, fighter.block_type])
    elif was_blocking and not fighter.is_blocking:
        print("[trace] blocking.released fighter=%s" % fighter.name)

func _desired_block_type(fighter) -> String:
    var can_block := true
    if fighter.get("can_block") != null:
        can_block = bool(fighter.get("can_block"))
    if not can_block:
        return "none"
    if bool(fighter.get("is_airborne")):
        return "none"
    if bool(fighter.get("is_stunned")) or int(fighter.get("stun_timer")) > 0:
        return "none"
    if int(fighter.get("hitstun_timer")) > 0:
        return "none"

    var action := str(fighter.get("current_action"))
    if _is_cpu_fighter(fighter):
        if test_mode == "guard_high":
            return "stand"
        if test_mode == "guard_low":
            return "crouch"
    if action == "block_high":
        return "stand"
    if action == "block_low":
        return "crouch"

    var buffer = fighter.get("input_buffer")
    if not (buffer is Array) or buffer.is_empty():
        return "none"

    var latest = buffer[buffer.size() - 1]
    if not (latest is Dictionary):
        return "none"

    var direction := str((latest as Dictionary).get("dir", "neutral"))
    if direction == "back":
        return "stand"
    if direction == "down_back":
        return "crouch"
    return "none"

func _is_cpu_fighter(fighter) -> bool:
    if fighter == null:
        return false
    if fighter.get("is_cpu") != null:
        return bool(fighter.get("is_cpu"))
    return int(fighter.get("player_slot") if fighter.get("player_slot") != null else 0) > 0
"""
