from __future__ import annotations


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    projectile_width = _float(constants, "projectile_hitbox_width", 84.0)
    projectile_height = _float(constants, "projectile_hitbox_height", 44.0)
    return f"""extends Node
## collision_system - generated by 2d_fighter template python
## Reads:  fighter.position, fighter.active_hitbox, fighter.current_action, fighter.facing_direction, fighter.is_crouching, fighter.is_airborne, projectile.position, projectile.owner_id, projectile.active
## Writes: fighter.hit_this_frame, fighter.hit_by_player_slot, fighter.hit_was_projectile, projectile.active, projectile.hit_landed

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _melee_contact_keys: Dictionary = {{}}

@export var projectile_hitbox_width: float = {projectile_width}
@export var projectile_hitbox_height: float = {projectile_height}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("projectile_hitbox_width"):
        projectile_hitbox_width = config["projectile_hitbox_width"] as float
    if config.has("projectile_hitbox_height"):
        projectile_hitbox_height = config["projectile_hitbox_height"] as float
    _melee_contact_keys.clear()

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    var projectiles: Array = entity_pools.get("projectiles", [])
    if fighters.size() < 2:
        return

    for fighter in fighters:
        if fighter == null:
            continue
        fighter.hit_this_frame = false
        fighter.hit_was_projectile = false
        fighter.hit_by_player_slot = ""

    for projectile in projectiles:
        if projectile == null:
            continue
        projectile.hit_landed = false

    _resolve_fighter_body_overlap(fighters[0], fighters[1])
    _prune_melee_registry(fighters)
    _check_melee_hit(fighters[0], fighters[1])
    _check_melee_hit(fighters[1], fighters[0])
    _check_projectile_clashes(projectiles)
    _check_projectile_hits(fighters, projectiles)

func _resolve_fighter_body_overlap(left_fighter, right_fighter) -> void:
    if left_fighter == null or right_fighter == null:
        return
    var left_rect := _rect_union(_fighter_hurtbox_rects(left_fighter))
    var right_rect := _rect_union(_fighter_hurtbox_rects(right_fighter))
    if not left_rect.intersects(right_rect):
        return

    var overlap_left: float = max(float(left_rect.position.x), float(right_rect.position.x))
    var overlap_right: float = min(float(left_rect.position.x + left_rect.size.x), float(right_rect.position.x + right_rect.size.x))
    var overlap_width: float = overlap_right - overlap_left
    if overlap_width <= 0.0:
        return

    var push_each := (overlap_width * 0.5) + 2.0
    if float(left_fighter.position.x) <= float(right_fighter.position.x):
        left_fighter.position.x -= push_each
        right_fighter.position.x += push_each
    else:
        left_fighter.position.x += push_each
        right_fighter.position.x -= push_each

    print("[trace] collision.pushout left=%s right=%s overlap=%.2f pos_left=%.2f pos_right=%.2f" % [
        left_fighter.name,
        right_fighter.name,
        overlap_width,
        float(left_fighter.position.x),
        float(right_fighter.position.x),
    ])

func _prune_melee_registry(fighters: Array) -> void:
    var alive: Array = []
    for fighter in fighters:
        if fighter != null:
            alive.append(fighter)
    var fighter_by_name: Dictionary = {{}}
    for fighter in alive:
        fighter_by_name[str(fighter.name)] = fighter

    var stale: Array = []
    for key in _melee_contact_keys.keys():
        var parts := str(key).split("|")
        if parts.size() < 3:
            stale.append(key)
            continue
        var attacker = fighter_by_name.get(parts[0])
        if attacker == null:
            stale.append(key)
            continue
        var action_name := parts[2]
        var active_hitbox = attacker.get("active_hitbox")
        if str(attacker.get("current_action")) != action_name:
            stale.append(key)
        elif not (active_hitbox is Dictionary) or (active_hitbox as Dictionary).is_empty():
            stale.append(key)

    for key in stale:
        _melee_contact_keys.erase(key)

func _check_melee_hit(attacker, defender) -> void:
    if attacker == null or defender == null:
        return
    var hitbox = attacker.get("active_hitbox")
    if not (hitbox is Dictionary) or (hitbox as Dictionary).is_empty():
        return

    var action_name := str((hitbox as Dictionary).get("action_name", attacker.get("current_action")))
    var registry_key := "%s|%s|%s" % [attacker.name, defender.name, action_name]
    if _melee_contact_keys.has(registry_key):
        return

    var hitbox_rects := _melee_hitbox_rects(attacker, hitbox as Dictionary)
    var hurtbox_rects := _fighter_hurtbox_rects(defender)
    if not _rect_arrays_intersect(hitbox_rects, hurtbox_rects):
        return
    var hitbox_rect := _rect_union(hitbox_rects)
    var hurtbox_rect := _rect_union(hurtbox_rects)

    defender.hit_this_frame = true
    defender.hit_was_projectile = false
    defender.hit_by_player_slot = _fighter_slot_id(attacker)
    _melee_contact_keys[registry_key] = true

    if sibling_systems.has("combat_system") and sibling_systems["combat_system"].has_method("queue_melee_hit"):
        sibling_systems["combat_system"].queue_melee_hit(attacker, defender, hitbox)

    print("[trace] collision.overlap attacker=%s attack=%s atk_rect=%s def_rect=%s result=hit" % [
        attacker.name,
        action_name,
        str(hitbox_rect),
        str(hurtbox_rect),
    ])

func _check_projectile_hits(fighters: Array, projectiles: Array) -> void:
    for projectile in projectiles:
        if projectile == null or not bool(projectile.get("active")):
            continue
        var projectile_rect := _projectile_rect(projectile)
        for fighter in fighters:
            if fighter == null:
                continue
            if str(projectile.get("owner_id")) == _fighter_slot_id(fighter):
                continue
            var hurtbox_rects := _fighter_hurtbox_rects(fighter)
            if not _rect_hits_any(projectile_rect, hurtbox_rects):
                continue
            var hurtbox_rect := _rect_union(hurtbox_rects)

            fighter.hit_this_frame = true
            fighter.hit_was_projectile = true
            fighter.hit_by_player_slot = str(projectile.get("owner_id"))
            projectile.active = false
            projectile.hit_landed = true

            if sibling_systems.has("combat_system") and sibling_systems["combat_system"].has_method("queue_projectile_hit"):
                sibling_systems["combat_system"].queue_projectile_hit(projectile, fighter, str(projectile.get("owner_id")))

            print("[trace] collision.overlap attacker=%s attack=projectile atk_rect=%s def_rect=%s result=hit" % [
                projectile.name,
                str(projectile_rect),
                str(hurtbox_rect),
            ])
            print("[trace] projectile.hit_landed id=%s target=%s" % [projectile.name, fighter.name])
            break

func _check_projectile_clashes(projectiles: Array) -> void:
    for i in range(projectiles.size()):
        var left = projectiles[i]
        if left == null or not bool(left.get("active")):
            continue
        var left_rect := _projectile_rect(left)
        for j in range(i + 1, projectiles.size()):
            var right = projectiles[j]
            if right == null or not bool(right.get("active")):
                continue
            if str(left.get("owner_id")) == str(right.get("owner_id")):
                continue
            var right_rect := _projectile_rect(right)
            if not left_rect.intersects(right_rect):
                continue
            left.active = false
            right.active = false
            left.hit_landed = true
            right.hit_landed = true
            print("[trace] projectile.clash left=%s right=%s rect_left=%s rect_right=%s" % [
                left.name,
                right.name,
                str(left_rect),
                str(right_rect),
            ])
            break

func _fighter_slot_id(fighter) -> String:
    var fighters: Array = entity_pools.get("fighters", [])
    var idx := fighters.find(fighter)
    if idx >= 0:
        return "P%d" % [idx + 1]
    var lower_name := str(fighter.name).to_lower()
    if lower_name.begins_with("p2"):
        return "P2"
    return "P1"

func _rect_like(value: Variant, fallback: Rect2) -> Rect2:
    if value is Rect2:
        return value as Rect2
    if value is Dictionary:
        var box: Dictionary = value as Dictionary
        if box.has("x") and box.has("y") and box.has("w") and box.has("h"):
            return Rect2(
                float(box.get("x", 0.0)) - (float(box.get("w", 0.0)) * 0.5),
                float(box.get("y", 0.0)) - float(box.get("h", 0.0)),
                float(box.get("w", 0.0)),
                float(box.get("h", 0.0))
            )
    return fallback

func _normalize_rect_array(value: Variant) -> Array:
    var rects: Array = []
    if value is Array:
        for entry in value:
            var rect := _rect_like(entry, Rect2())
            if rect.size.x > 0.0 and rect.size.y > 0.0:
                rects.append(rect)
        return rects
    var single := _rect_like(value, Rect2())
    if single.size.x > 0.0 and single.size.y > 0.0:
        rects.append(single)
    return rects

func _local_rects_to_world(entity, rects: Array) -> Array:
    var world_rects: Array = []
    for entry in rects:
        if not (entry is Rect2):
            continue
        var rect: Rect2 = entry as Rect2
        world_rects.append(
            Rect2(
                Vector2(float(entity.position.x) + rect.position.x, float(entity.position.y) + rect.position.y),
                rect.size
            )
        )
    return world_rects

func _rect_union(rects: Array) -> Rect2:
    var merged := Rect2()
    var has_rect := false
    for entry in rects:
        if not (entry is Rect2):
            continue
        var rect: Rect2 = entry as Rect2
        if rect.size.x <= 0.0 or rect.size.y <= 0.0:
            continue
        if not has_rect:
            merged = rect
            has_rect = true
        else:
            merged = merged.merge(rect)
    return merged if has_rect else Rect2()

func _rect_arrays_intersect(left_rects: Array, right_rects: Array) -> bool:
    for left in left_rects:
        if not (left is Rect2):
            continue
        for right in right_rects:
            if right is Rect2 and (left as Rect2).intersects(right as Rect2):
                return true
    return false

func _rect_hits_any(rect: Rect2, candidates: Array) -> bool:
    for candidate in candidates:
        if candidate is Rect2 and rect.intersects(candidate as Rect2):
            return true
    return false

func _fighter_hurtbox_rects(fighter) -> Array:
    if fighter != null and fighter.has_method("rayxi_hurtbox_rects_local"):
        var local_rects := _normalize_rect_array(fighter.call("rayxi_hurtbox_rects_local"))
        if not local_rects.is_empty():
            return _local_rects_to_world(fighter, local_rects)
    var fallback := Rect2(-60.0, -180.0, 120.0, 180.0)
    var hurtbox: Rect2 = _rect_like(fighter.get("stand_hurtbox"), fallback)
    if bool(fighter.get("is_airborne")):
        hurtbox = _rect_like(fighter.get("air_hurtbox"), hurtbox)
    elif bool(fighter.get("is_crouching")):
        hurtbox = _rect_like(fighter.get("crouch_hurtbox"), hurtbox)
    return _local_rects_to_world(fighter, [hurtbox])

func _fighter_hurtbox_rect(fighter) -> Rect2:
    return _rect_union(_fighter_hurtbox_rects(fighter))

func _melee_hitbox_rects(attacker, hitbox: Dictionary) -> Array:
    if attacker != null and attacker.has_method("rayxi_active_hitbox_rects_local"):
        var local_rects := _normalize_rect_array(attacker.call("rayxi_active_hitbox_rects_local", hitbox))
        if not local_rects.is_empty():
            return _local_rects_to_world(attacker, local_rects)
    var facing := 1 if int(attacker.get("facing_direction")) >= 0 else -1
    var width: float = max(float(hitbox.get("width", 80.0)), 8.0)
    var height: float = max(float(hitbox.get("height", 80.0)), 8.0)
    var offset_x: float = float(hitbox.get("offset_x", 0.0)) * facing
    var offset_y: float = float(hitbox.get("offset_y", 0.0))
    return _local_rects_to_world(
        attacker,
        [Rect2(Vector2(offset_x - (width * 0.5), offset_y - height), Vector2(width, height))]
    )

func _melee_hitbox_rect(attacker, hitbox: Dictionary) -> Rect2:
    return _rect_union(_melee_hitbox_rects(attacker, hitbox))

func _projectile_rect(projectile) -> Rect2:
    var width := float(projectile.get("hitbox_width") if projectile.get("hitbox_width") != null else projectile_hitbox_width)
    var height := float(projectile.get("hitbox_height") if projectile.get("hitbox_height") != null else projectile_hitbox_height)
    return Rect2(
        Vector2(float(projectile.position.x) - (width * 0.5), float(projectile.position.y) - (height * 0.5)),
        Vector2(width, height)
    )
"""
