from __future__ import annotations

from rayxi.build.template_codegen import resolve_property_name


def _int(constants: dict | None, *names: str, default: int) -> str:
    if constants:
        for name in names:
            if name in constants:
                return str(int(constants[name]))
    return str(int(default))


def emit_system(slice_data, hlr, spec, constants) -> str:
    max_health = _int(constants, "max_health", "max_hp", default=1000)
    light_hitstop = _int(constants, "hitstop_light", "hitstop_frames", default=8)
    medium_hitstop = _int(constants, "hitstop_medium", default=12)
    heavy_hitstop = _int(constants, "hitstop_heavy", default=16)
    special_hitstop = _int(constants, "hitstop_special", default=18)
    projectile_powered_prop = resolve_property_name(
        slice_data,
        "projectile",
        ("is_powered", "is_powered_up"),
        default="is_powered",
    )
    return f"""extends Node
## combat_system - generated by 2d_fighter template python
## Reads:  fighter.current_action, fighter.action_frame, fighter.current_health, fighter.block_type, fighter.is_blocking, fighter.combo_damage_scaling, fighter.facing_direction, fighter.position, fighter.is_powered_special, fighter.hit_this_frame, fighter.hit_was_projectile, fighter.hit_by_player_slot, game.round_state
## Writes: fighter.active_hitbox, fighter.attack_hit_level, fighter.current_health, fighter.is_ko, fighter.hitstop_timer, fighter.hitstun_timer, fighter.blockstun_timer, fighter.pushback_velocity, fighter.damage_taken_this_frame, fighter.is_counter_hit

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _pending_hits: Array = []

@export var max_health: int = {max_health}
@export var hitstop_light: int = {light_hitstop}
@export var hitstop_medium: int = {medium_hitstop}
@export var hitstop_heavy: int = {heavy_hitstop}
@export var hitstop_special: int = {special_hitstop}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("max_health"):
        max_health = config["max_health"] as int
    elif config.has("max_hp"):
        max_health = config["max_hp"] as int
    if config.has("hitstop_light"):
        hitstop_light = config["hitstop_light"] as int
    if config.has("hitstop_medium"):
        hitstop_medium = config["hitstop_medium"] as int
    if config.has("hitstop_heavy"):
        hitstop_heavy = config["hitstop_heavy"] as int
    if config.has("hitstop_special"):
        hitstop_special = config["hitstop_special"] as int
    _pending_hits.clear()

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var round_state := _current_round_state()
    var fighters: Array = entity_pools.get("fighters", [])
    for fighter in fighters:
        if fighter == null:
            continue
        _tick_fighter(fighter)
        _update_active_hitbox(fighter)
    if round_state != "fighting":
        _pending_hits.clear()
        return
    _drain_pending_hits()

func queue_melee_hit(attacker, defender, hitbox: Dictionary) -> void:
    if attacker == null or defender == null or hitbox.is_empty():
        return
    _pending_hits.append({{
        "type": "melee",
        "attacker": attacker,
        "defender": defender,
        "attacker_slot": _fighter_slot_id(attacker),
        "hitbox": hitbox.duplicate(true),
        "source": str(hitbox.get("action_name", "melee")),
    }})

func queue_projectile_hit(projectile, defender, attacker_slot: String) -> void:
    if projectile == null or defender == null:
        return
    var hitbox := {{
        "action_name": "special_projectile",
        "damage": int(projectile.get("damage") if projectile.get("damage") != null else 60),
        "hitstun": int(projectile.get("hitstun_frames") if projectile.get("hitstun_frames") != null else 16),
        "blockstun": 12,
        "pushback": 56.0,
        "hit_level": "mid",
        "stun_value": 20,
        "powered": bool(projectile.get("{projectile_powered_prop}")),
        "source": str(projectile.name),
    }}
    _pending_hits.append({{
        "type": "projectile",
        "attacker": _fighter_by_slot(attacker_slot),
        "defender": defender,
        "attacker_slot": attacker_slot,
        "hitbox": hitbox,
        "source": str(projectile.name),
    }})

func _current_round_state() -> String:
    var parent = get_parent()
    if parent != null:
        var scene_state = parent.get("round_state")
        if scene_state != null:
            return str(scene_state)
    if sibling_systems.has("round_system"):
        var round_state = sibling_systems["round_system"].get("round_state")
        if round_state != null:
            return str(round_state)
    return "fighting"

func _tick_fighter(fighter) -> void:
    fighter.damage_taken_this_frame = 0
    fighter.hit_this_frame = false
    if int(fighter.hitstop_timer) > 0:
        fighter.hitstop_timer = max(int(fighter.hitstop_timer) - 1, 0)
    if int(fighter.hitstun_timer) > 0:
        fighter.hitstun_timer = max(int(fighter.hitstun_timer) - 1, 0)
    if int(fighter.hitstun_timer) == 0:
        fighter.is_counter_hit = false
    if fighter.get("current_health") == null and fighter.get("current_hp") != null:
        fighter.set("current_health", int(fighter.get("current_hp")))
    if fighter.get("max_health") == null and fighter.get("max_hp") != null:
        fighter.set("max_health", int(fighter.get("max_hp")))

func _update_active_hitbox(fighter) -> void:
    var action := str(fighter.current_action)
    var profile := _attack_profile(fighter, action)
    if profile.is_empty():
        fighter.active_hitbox = {{}}
        fighter.attack_hit_level = "none"
        return
    var startup := int(profile.get("startup", 0))
    var active := int(profile.get("active", 0))
    var frame := int(fighter.action_frame)
    if frame < startup or frame >= startup + active:
        fighter.active_hitbox = {{}}
        fighter.attack_hit_level = "none"
        return

    var offset: Variant = profile.get("offset")
    if not (offset is Vector2):
        offset = Vector2(80.0, -90.0)
    var hitbox_width := float(profile.get("width", 80.0))
    var hitbox_height := float(profile.get("height", 80.0))
    var offset_x := float((offset as Vector2).x)
    var offset_y := float((offset as Vector2).y)
    if action == "special_uppercut":
        var active_progress := clampf(float(frame - startup) / float(max(active - 1, 1)), 0.0, 1.0)
        hitbox_width = max(hitbox_width - (active_progress * 14.0), 156.0)
        hitbox_height = max(hitbox_height + (active_progress * 54.0), 204.0)
        offset_x = min(offset_x + (active_progress * 12.0), 64.0)
        offset_y = offset_y - (active_progress * 68.0)
    fighter.active_hitbox = {{
        "action_name": action,
        "damage": int(profile.get("damage", 0)),
        "hitstun": int(profile.get("hitstun", 12)),
        "blockstun": int(profile.get("blockstun", 10)),
        "pushback": float(profile.get("pushback", 48.0)),
        "hit_level": str(profile.get("hit_level", "high")),
        "width": hitbox_width,
        "height": hitbox_height,
        "offset_x": offset_x,
        "offset_y": offset_y,
        "stun_value": int(profile.get("stun_value", 12)),
    }}
    fighter.attack_hit_level = str(profile.get("hit_level", "high"))

func _attack_profile(fighter, action: String) -> Dictionary:
    if action == "" or action in ["idle", "intro", "victory", "ko", "block_high", "block_low", "hit_high", "hit_low", "hit_airborne", "stunned", "special_projectile"]:
        return {{}}
    if action == "special_uppercut":
        return _special_profile(fighter, "shoryuken", {{
            "startup": 1,
            "active": 16,
            "recovery": 33,
            "damage": 140,
            "stun_value": 28,
            "width": 176.0,
            "height": 204.0,
            "offset": Vector2(52.0, -22.0),
            "max_startup": 3,
            "min_active": 16,
            "hit_level": "high",
        }})
    if action == "special_spinning":
        return _special_profile(fighter, "tatsumaki_senpuukyaku", {{
            "startup": 11,
            "active": 24,
            "recovery": 16,
            "damage": 110,
            "stun_value": 24,
            "width": 120.0,
            "height": 92.0,
            "offset": Vector2(90.0, -100.0),
            "hit_level": "mid",
        }})
    return _normal_profile(fighter, action)

func _normal_profile(fighter, action: String) -> Dictionary:
    if fighter.get(action + "_startup") == null:
        return {{}}
    var hits_low := bool(fighter.get(action + "_hits_low") if fighter.get(action + "_hits_low") != null else false)
    var is_overhead := bool(fighter.get(action + "_is_overhead") if fighter.get(action + "_is_overhead") != null else action.begins_with("jump_"))
    var hit_level := "high"
    if hits_low:
        hit_level = "low"
    elif action.begins_with("jump_") or is_overhead:
        hit_level = "high"
    var offset = fighter.get(action + "_hitbox_offset")
    if not (offset is Vector2):
        offset = Vector2(80.0, -100.0)
    return {{
        "startup": int(fighter.get(action + "_startup")),
        "active": int(fighter.get(action + "_active") if fighter.get(action + "_active") != null else 2),
        "recovery": int(fighter.get(action + "_recovery") if fighter.get(action + "_recovery") != null else 8),
        "damage": int(fighter.get(action + "_damage") if fighter.get(action + "_damage") != null else 30),
        "hitstun": int(fighter.get(action + "_hitstun") if fighter.get(action + "_hitstun") != null else 12),
        "blockstun": int(fighter.get(action + "_blockstun") if fighter.get(action + "_blockstun") != null else 10),
        "stun_value": int(fighter.get(action + "_stun_value") if fighter.get(action + "_stun_value") != null else 12),
        "width": float(fighter.get(action + "_hitbox_w") if fighter.get(action + "_hitbox_w") != null else 80.0),
        "height": float(fighter.get(action + "_hitbox_h") if fighter.get(action + "_hitbox_h") != null else 80.0),
        "offset": offset,
        "pushback": _pushback_for_damage(int(fighter.get(action + "_damage") if fighter.get(action + "_damage") != null else 30)),
        "hit_level": hit_level,
    }}

func _special_profile(fighter, prefix: String, defaults: Dictionary) -> Dictionary:
    var damage := int(fighter.get(prefix + "_damage") if fighter.get(prefix + "_damage") != null else defaults.get("damage", 90))
    var startup := _special_window_value(
        fighter.get(prefix + "_startup"),
        int(defaults.get("startup", 8)),
        int(defaults.get("min_startup", 1)),
        int(defaults.get("max_startup", max(int(defaults.get("startup", 8)) + 6, 8)))
    )
    var active := _special_window_value(
        fighter.get(prefix + "_active"),
        int(defaults.get("active", 10)),
        int(defaults.get("min_active", max(int(int(defaults.get("active", 10)) / 2), 4))),
        int(defaults.get("max_active", max(int(defaults.get("active", 10)) + 10, 12)))
    )
    var recovery := _special_window_value(
        fighter.get(prefix + "_recovery"),
        int(defaults.get("recovery", 18)),
        int(defaults.get("min_recovery", max(int(int(defaults.get("recovery", 18)) / 2), 8))),
        int(defaults.get("max_recovery", max(int(defaults.get("recovery", 18)) * 2, 20)))
    )
    var hits_low := bool(fighter.get(prefix + "_hits_low") if fighter.get(prefix + "_hits_low") != null else false)
    var hit_level := str(defaults.get("hit_level", "mid"))
    if hits_low:
        hit_level = "low"
    return {{
        "startup": startup,
        "active": active,
        "recovery": recovery,
        "damage": damage,
        "hitstun": max(14, int(round(float(damage) * 0.18))),
        "blockstun": max(10, int(round(float(damage) * 0.12))),
        "stun_value": int(fighter.get(prefix + "_stun_value") if fighter.get(prefix + "_stun_value") != null else defaults.get("stun_value", 24)),
        "width": float(defaults.get("width", 90.0)),
        "height": float(defaults.get("height", 96.0)),
        "offset": defaults.get("offset", Vector2(80.0, -110.0)),
        "pushback": _pushback_for_damage(damage),
        "hit_level": hit_level,
    }}

func _special_window_value(raw_value: Variant, fallback: int, minimum: int, maximum: int) -> int:
    var value := fallback if raw_value == null else int(raw_value)
    return clampi(value, minimum, max(minimum, maximum))

func _pushback_for_damage(damage: int) -> float:
    if damage >= 120:
        return 86.0
    if damage >= 80:
        return 68.0
    if damage >= 50:
        return 54.0
    return 38.0

func _fighter_slot_id(fighter) -> String:
    var fighters: Array = entity_pools.get("fighters", [])
    var idx := fighters.find(fighter)
    if idx >= 0:
        return "P%d" % [idx + 1]
    var lower_name := str(fighter.name).to_lower()
    if lower_name.begins_with("p2"):
        return "P2"
    return "P1"

func _fighter_by_slot(slot_id: String):
    for fighter in entity_pools.get("fighters", []):
        if fighter != null and _fighter_slot_id(fighter) == slot_id:
            return fighter
    return null

func _drain_pending_hits() -> void:
    if _pending_hits.is_empty():
        return
    var queued := _pending_hits.duplicate(true)
    _pending_hits.clear()
    for event in queued:
        _apply_hit_event(event)

func _apply_hit_event(event: Dictionary) -> void:
    var defender = event.get("defender")
    if defender == null:
        return
    if bool(defender.get("is_ko")):
        return

    var attacker = event.get("attacker")
    var hitbox = event.get("hitbox", {{}})
    if not (hitbox is Dictionary) or (hitbox as Dictionary).is_empty():
        return

    var hit_level := str(hitbox.get("hit_level", "high"))
    var blocked := _is_blocked(defender, hit_level)
    var base_damage := int(hitbox.get("damage", 0))
    if attacker != null and bool(attacker.get("is_powered_special")):
        base_damage = int(round(float(base_damage) * 1.5))
    elif bool(hitbox.get("powered", false)):
        base_damage = int(round(float(base_damage) * 1.5))

    var counter_hit := _is_counter_hit(defender)
    if counter_hit and not blocked:
        base_damage = int(round(float(base_damage) * 1.25))

    var scaling: float = float(defender.get("combo_damage_scaling") if defender.get("combo_damage_scaling") != null else 1.0)
    var final_damage: int = max(int(round(float(base_damage) * scaling)), 1)
    var chip_multiplier: float = float(defender.get("chip_damage_multiplier") if defender.get("chip_damage_multiplier") != null else 0.1)
    var applied_damage: int = final_damage

    defender.hit_this_frame = true
    defender.damage_taken_this_frame = applied_damage
    defender.is_counter_hit = counter_hit

    if blocked:
        applied_damage = max(int(round(float(final_damage) * chip_multiplier)), 1)
        defender.damage_taken_this_frame = applied_damage
        defender.blockstun_timer = int(hitbox.get("blockstun", 10))
        defender.hitstun_timer = 0
        print("[trace] combat.blocked defender=%s attacker=%s move=%s chip=%d blockstun=%d" % [
            defender.name,
            _event_attacker_name(event),
            str(hitbox.get("action_name", "attack")),
            applied_damage,
            defender.blockstun_timer,
        ])
    else:
        defender.hitstun_timer = int(hitbox.get("hitstun", 12))
        defender.blockstun_timer = 0
        print("[trace] combat.hit attacker=%s defender=%s move=%s damage=%d counter=%s remaining_hp=%d" % [
            _event_attacker_name(event),
            defender.name,
            str(hitbox.get("action_name", "attack")),
            applied_damage,
            counter_hit,
            max(int(defender.get("current_health")) - applied_damage, 0),
        ])

    var current_health := int(defender.get("current_health") if defender.get("current_health") != null else max_health)
    defender.current_health = max(current_health - applied_damage, 0)
    defender.is_ko = defender.current_health <= 0
    defender.pushback_velocity = _pushback_velocity(attacker, defender, float(hitbox.get("pushback", 48.0)))

    var hitstop := _hitstop_for_hitbox(hitbox)
    defender.hitstop_timer = hitstop
    if attacker != null:
        attacker.hitstop_timer = hitstop

    if sibling_systems.has("stun_system") and sibling_systems["stun_system"].has_method("process_damage_event"):
        sibling_systems["stun_system"].process_damage_event(defender, applied_damage)
    if sibling_systems.has("rage_meter_system") and sibling_systems["rage_meter_system"].has_method("process_damage_event"):
        sibling_systems["rage_meter_system"].process_damage_event(defender, applied_damage)

func _pushback_velocity(attacker, defender, amount: float) -> float:
    if attacker != null:
        return amount if float(defender.position.x) >= float(attacker.position.x) else -amount
    var slot_id := str(defender.get("hit_by_player_slot"))
    if slot_id == "P1":
        return amount
    if slot_id == "P2":
        return -amount
    return amount

func _event_attacker_name(event: Dictionary) -> String:
    var attacker = event.get("attacker")
    if attacker != null:
        return str(attacker.name)
    var source := str(event.get("source", "unknown"))
    if source != "":
        return source
    return str(event.get("attacker_slot", "unknown"))

func _is_blocked(defender, hit_level: String) -> bool:
    if not bool(defender.get("is_blocking")):
        return false
    var block_type := str(defender.get("block_type"))
    if hit_level == "low":
        return block_type == "crouch"
    if hit_level == "throw":
        return false
    return block_type in ["stand", "crouch"]

func _is_counter_hit(defender) -> bool:
    var action := str(defender.get("current_action"))
    var profile := _attack_profile(defender, action)
    if profile.is_empty():
        return false
    return int(defender.get("action_frame")) < int(profile.get("startup", 0)) + int(profile.get("active", 0))

func _hitstop_for_hitbox(hitbox: Dictionary) -> int:
    var damage := int(hitbox.get("damage", 0))
    var action_name := str(hitbox.get("action_name", ""))
    if action_name.begins_with("special_"):
        return hitstop_special
    if damage >= 100:
        return hitstop_heavy
    if damage >= 60:
        return hitstop_medium
    return hitstop_light
"""
