from __future__ import annotations


def _int(constants: dict | None, *names: str, default: int) -> str:
    if constants:
        for name in names:
            if name in constants:
                return str(int(constants[name]))
    return str(int(default))


def _available_props(slice_data: dict) -> set[str]:
    names: set[str] = set()
    for detail_id in (slice_data.get("property_details") or {}):
        if "." in detail_id:
            names.add(detail_id.split(".", 1)[1])
    for node in slice_data.get("owned_properties", []) or []:
        for key in ("name", "id"):
            value = node.get(key)
            if isinstance(value, str):
                names.add(value.split(".", 1)[1] if "." in value else value)
    for edge in slice_data.get("own_reads", []) or []:
        source = edge.get("source")
        if isinstance(source, str):
            names.add(source.split(".", 1)[1] if "." in source else source)
    for edge in slice_data.get("own_writes", []) or []:
        target = edge.get("target")
        if isinstance(target, str):
            names.add(target.split(".", 1)[1] if "." in target else target)
    return names


def emit_system(slice_data, hlr, spec, constants) -> str:
    props = _available_props(slice_data)
    current_health = "current_health" if "current_health" in props or "current_hp" not in props else "current_hp"
    max_health = "max_health" if "max_health" in props or "max_hp" not in props else "max_hp"
    max_health_default = _int(constants, "max_health", "max_hp", default=1000)
    return f"""extends Node
## health_system - generated by 2d_fighter template python
## Reads:  fighter.{current_health}, fighter.{max_health}, hud_bar.target_property, hud_bar.max_property
## Writes: fighter.{current_health}, fighter.{max_health}, fighter.is_ko, hud_bar.display_value

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}

@export var max_health: int = {max_health_default}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("max_health"):
        max_health = config["max_health"] as int
    elif config.has("max_hp"):
        max_health = config["max_hp"] as int

    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        if fighter.get("{max_health}") == null or int(fighter.get("{max_health}")) <= 0:
            fighter.set("{max_health}", max_health)
        if fighter.get("{current_health}") == null or int(fighter.get("{current_health}")) <= 0:
            fighter.set("{current_health}", int(fighter.get("{max_health}")))
        fighter.is_ko = int(fighter.get("{current_health}")) <= 0

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    for fighter in fighters:
        if fighter == null:
            continue
        var current_raw: Variant = fighter.get("{current_health}")
        var max_raw: Variant = fighter.get("{max_health}")
        var current_value: int = max(int(0 if current_raw == null else current_raw), 0)
        var max_value: int = max(int(1 if max_raw == null else max_raw), 1)
        if current_value != int(fighter.get("{current_health}")):
            fighter.set("{current_health}", current_value)
        fighter.is_ko = current_value <= 0
        if max_value != int(fighter.get("{max_health}")):
            fighter.set("{max_health}", max_value)

    var hud_bars: Array = entity_pools.get("hud_bars", [])
    for i in range(min(fighters.size(), hud_bars.size())):
        var fighter = fighters[i]
        var hud_bar = hud_bars[i]
        if fighter == null or hud_bar == null:
            continue
        var target_property := str(hud_bar.get("target_property"))
        var max_property := str(hud_bar.get("max_property"))
        if target_property == "":
            target_property = "{current_health}"
        if max_property == "":
            max_property = "{max_health}"
        var raw_value: Variant = fighter.get(target_property)
        if raw_value == null and target_property == "current_health":
            raw_value = fighter.get("current_hp")
        elif raw_value == null and target_property == "current_hp":
            raw_value = fighter.get("current_health")
        var raw_max: Variant = fighter.get(max_property)
        if raw_max == null and max_property == "max_health":
            raw_max = fighter.get("max_hp")
        elif raw_max == null and max_property == "max_hp":
            raw_max = fighter.get("max_health")
        var current_display: float = float(0 if raw_value == null else raw_value)
        var max_display: float = max(float(1 if raw_max == null else raw_max), 1.0)
        var next_ratio := clampf(current_display / max_display, 0.0, 1.0)
        var previous_ratio := float(hud_bar.get("display_value") if hud_bar.get("display_value") != null else hud_bar.get("value"))
        hud_bar.display_value = next_ratio
        if absf(previous_ratio - next_ratio) > 0.005:
            print("[trace] hud.health_update fighter=%s bar=%s ratio=%.3f current=%d max=%d" % [
                fighter.name,
                hud_bar.name,
                next_ratio,
                int(current_display),
                int(max_display),
            ])

func process_round_start() -> void:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        fighter.set("{max_health}", max_health)
        fighter.set("{current_health}", max_health)
        fighter.is_ko = false
        print("[trace] health.round_start fighter=%s max_health=%d current_health=%d" % [
            fighter.name,
            max_health,
            max_health,
        ])

func process_damage_event(fighter, damage: int, source: String = "") -> void:
    if fighter == null or damage <= 0:
        return
    var old_value: int = int(fighter.get("{current_health}"))
    var new_value: int = max(old_value - damage, 0)
    fighter.set("{current_health}", new_value)
    fighter.is_ko = new_value <= 0
    print("[trace] health.damage fighter=%s damage=%d old=%d new=%d source=%s" % [
        fighter.name,
        damage,
        old_value,
        new_value,
        source,
    ])
    if fighter.is_ko:
        print("[trace] health.ko fighter=%s final_damage_source=%s" % [fighter.name, source])
"""
