from __future__ import annotations


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    input_buffer_max_size = _int(constants, "input_buffer_max_size", 20)
    input_buffer_valid_frames = _int(constants, "input_buffer_valid_frames", 15)
    return f"""extends Node
## input_system — generated by 2d_fighter template python
## Reads:  fighter.hitstop_timer, fighter.hitstun_timer, fighter.blockstun_timer, fighter.facing_direction, fighter.is_airborne, fighter.stun_timer, fighter.is_stunned, fighter.projectile_on_screen, fighter.is_firing_projectile, fighter.input_buffer, fighter.special_cooldown_timer, fighter.ai_current_plan, game.round_state, fighter.input_light_punch, fighter.input_medium_punch, fighter.input_heavy_punch, fighter.input_light_kick, fighter.input_medium_kick, fighter.input_heavy_kick, fighter.rage_stacks
## Writes: fighter.is_crouching, fighter.input_buffer, fighter.current_action, fighter.action_frame, fighter.input_light_punch, fighter.input_medium_punch, fighter.input_heavy_punch, fighter.input_light_kick, fighter.input_medium_kick, fighter.input_heavy_kick

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}

@export var input_buffer_max_size: int = {input_buffer_max_size}
@export var input_buffer_valid_frames: int = {input_buffer_valid_frames}
@export var test_mode: String = ""

var _frame_counter: int = 0

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("input_buffer_max_size"):
        input_buffer_max_size = config["input_buffer_max_size"] as int
    if config.has("input_buffer_valid_frames"):
        input_buffer_valid_frames = config["input_buffer_valid_frames"] as int
    if config.has("test_mode"):
        test_mode = str(config["test_mode"])
    _frame_counter = 0

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    _frame_counter += 1

    var fighters: Array = entity_pools.get("fighters", [])
    if fighters.is_empty():
        return

    var round_state: String = _current_round_state()
    for i in range(fighters.size()):
        var fighter = fighters[i]
        if fighter == null:
            continue
        _process_fighter(fighter, i, round_state)

func _process_fighter(fighter, fighter_index: int, round_state: String) -> void:
    var prev_action: String = str(fighter.current_action)
    var was_crouching: bool = bool(fighter.is_crouching)
    var hitstop_timer: int = int(fighter.hitstop_timer)
    var hitstun_timer: int = int(fighter.hitstun_timer)
    var blockstun_timer: int = int(fighter.blockstun_timer)
    var stun_timer: int = int(fighter.stun_timer)
    var is_stunned: bool = bool(fighter.is_stunned)
    var is_airborne: bool = bool(fighter.is_airborne)
    var facing_direction: int = int(fighter.facing_direction)
    var projectile_on_screen: int = int(fighter.projectile_on_screen)
    var is_firing_projectile: bool = bool(fighter.is_firing_projectile)
    var special_cooldown: int = int(fighter.special_cooldown_timer)
    var rage_stacks: int = int(fighter.rage_stacks)
    var ai_plan: String = str(fighter.ai_current_plan)
    var action_frame: int = int(fighter.action_frame)

    var input_left := false
    var input_right := false
    var input_down := false
    var input_up := false
    var input_lp := false
    var input_mp := false
    var input_hp := false
    var input_lk := false
    var input_mk := false
    var input_hk := false
    var forced_action := ""

    if round_state != "fighting":
        _clear_attack_inputs(fighter)
        fighter.is_crouching = false
        fighter.input_buffer = []
        if was_crouching:
            print("[trace] input.crouch_change fighter=%s crouching=false" % fighter.name)
        var gated_action := "intro" if round_state == "pre_round" else "idle"
        if round_state == "match_over" and not bool(fighter.is_ko):
            gated_action = "victory"
        elif bool(fighter.is_ko):
            gated_action = "ko"
        _apply_action(fighter, prev_action, gated_action)
        return

    if fighter_index == 0:
        input_left = Input.is_action_pressed("p1_left")
        input_right = Input.is_action_pressed("p1_right")
        input_down = Input.is_action_pressed("p1_down")
        input_up = Input.is_action_pressed("p1_up")
        input_lp = Input.is_action_pressed("p1_light_punch")
        input_mp = Input.is_action_pressed("p1_medium_punch")
        input_hp = Input.is_action_pressed("p1_heavy_punch")
        input_lk = Input.is_action_pressed("p1_light_kick")
        input_mk = Input.is_action_pressed("p1_medium_kick")
        input_hk = Input.is_action_pressed("p1_heavy_kick")
    else:
        var cpu_decision := _cpu_action_for_plan(fighter, ai_plan, prev_action)
        forced_action = cpu_decision.get("action", "")
        input_left = bool(cpu_decision.get("left", false))
        input_right = bool(cpu_decision.get("right", false))
        input_down = bool(cpu_decision.get("down", false))
        input_up = bool(cpu_decision.get("up", false))
        input_lp = bool(cpu_decision.get("lp", false))
        input_mp = bool(cpu_decision.get("mp", false))
        input_hp = bool(cpu_decision.get("hp", false))
        input_lk = bool(cpu_decision.get("lk", false))
        input_mk = bool(cpu_decision.get("mk", false))
        input_hk = bool(cpu_decision.get("hk", false))

    fighter.input_light_punch = input_lp
    fighter.input_medium_punch = input_mp
    fighter.input_heavy_punch = input_hp
    fighter.input_light_kick = input_lk
    fighter.input_medium_kick = input_mk
    fighter.input_heavy_kick = input_hk

    fighter.is_crouching = input_down
    if was_crouching != bool(fighter.is_crouching):
        print("[trace] input.crouch_change fighter=%s crouching=%s" % [fighter.name, fighter.is_crouching])

    var rel_horizontal := 0
    if input_left:
        rel_horizontal = -1 if facing_direction == 1 else 1
    elif input_right:
        rel_horizontal = 1 if facing_direction == 1 else -1

    var current_dir := "neutral"
    if input_down:
        if rel_horizontal == -1:
            current_dir = "down_back"
        elif rel_horizontal == 1:
            current_dir = "down_forward"
        else:
            current_dir = "down"
    elif input_up:
        if rel_horizontal == -1:
            current_dir = "up_back"
        elif rel_horizontal == 1:
            current_dir = "up_forward"
        else:
            current_dir = "up"
    else:
        if rel_horizontal == -1:
            current_dir = "back"
        elif rel_horizontal == 1:
            current_dir = "forward"

    var buffer = fighter.input_buffer as Array
    if buffer == null:
        buffer = []
    var last_direction: String = ""
    if buffer.size() > 0:
        var last_entry: Dictionary = buffer[buffer.size() - 1] as Dictionary
        last_direction = str(last_entry.get("dir", ""))
    if buffer.is_empty() or last_direction != current_dir:
        buffer.append({{"dir": current_dir, "frame": _frame_counter}})
    while buffer.size() > input_buffer_max_size:
        buffer.pop_front()
    var cutoff: int = _frame_counter - max(input_buffer_valid_frames, 30)
    while buffer.size() > 0 and int((buffer[0] as Dictionary).get("frame", 0)) < cutoff:
        buffer.pop_front()
    fighter.input_buffer = buffer

    var input_blocked := (hitstop_timer > 0) or (hitstun_timer > 0) or (blockstun_timer > 0) or is_stunned or (stun_timer > 0)
    var new_action: String = prev_action
    var any_attack_pressed := input_lp or input_mp or input_hp or input_lk or input_mk or input_hk

    if input_blocked:
        if stun_timer > 0 or is_stunned:
            new_action = "stunned"
        elif hitstun_timer > 0:
            if is_airborne:
                new_action = "hit_airborne"
            elif prev_action.begins_with("crouch") or prev_action == "crouch":
                new_action = "hit_low"
            else:
                new_action = "hit_high"
        elif blockstun_timer > 0:
            new_action = "block_low" if bool(fighter.is_crouching) else "block_high"
    else:
        if _should_preserve_action(prev_action, action_frame, is_airborne):
            _apply_action(fighter, prev_action, prev_action)
            return
        if forced_action != "":
            new_action = forced_action
        else:
            var any_punch := input_lp or input_mp or input_hp
            var any_kick := input_lk or input_mk or input_hk
            var special_detected := ""
            if special_cooldown == 0 and not is_firing_projectile:
                if _check_motion(buffer, ["down", "down_forward", "forward"]):
                    if any_punch:
                        special_detected = "special_projectile"
                elif _check_motion(buffer, ["forward", "down", "down_forward"]):
                    if any_punch:
                        special_detected = "special_uppercut"
                elif _check_motion(buffer, ["down", "down_back", "back"]):
                    if any_kick:
                        special_detected = "special_spinning"

            if special_detected != "":
                if special_detected == "special_projectile" and projectile_on_screen > 0:
                    pass
                else:
                    new_action = special_detected
                    print("[trace] input.special_detected fighter=%s move=%s powered=%s" % [
                        fighter.name,
                        special_detected,
                        rage_stacks > 0,
                    ])
            elif any_punch or any_kick:
                if is_airborne:
                    if input_lp: new_action = "jump_light_punch"
                    elif input_mp: new_action = "jump_medium_punch"
                    elif input_hp: new_action = "jump_heavy_punch"
                    elif input_lk: new_action = "jump_light_kick"
                    elif input_mk: new_action = "jump_medium_kick"
                    elif input_hk: new_action = "jump_heavy_kick"
                elif bool(fighter.is_crouching):
                    if input_lp: new_action = "crouch_light_punch"
                    elif input_mp: new_action = "crouch_medium_punch"
                    elif input_hp: new_action = "crouch_heavy_punch"
                    elif input_lk: new_action = "crouch_light_kick"
                    elif input_mk: new_action = "crouch_medium_kick"
                    elif input_hk: new_action = "crouch_heavy_kick"
                else:
                    if input_lp: new_action = "light_punch"
                    elif input_mp: new_action = "medium_punch"
                    elif input_hp: new_action = "heavy_punch"
                    elif input_lk: new_action = "light_kick"
                    elif input_mk: new_action = "medium_kick"
                    elif input_hk: new_action = "heavy_kick"
                if test_mode != "":
                    print("[trace] input.special_miss fighter=%s dir=%s buffer=%s cooldown=%d projectile_on_screen=%d firing=%s" % [
                        fighter.name,
                        current_dir,
                        str(_motion_tail(buffer)),
                        special_cooldown,
                        projectile_on_screen,
                        str(is_firing_projectile),
                    ])
            elif input_up:
                if rel_horizontal == -1:
                    new_action = "jump_back"
                elif rel_horizontal == 1:
                    new_action = "jump_forward"
                else:
                    new_action = "jump_neutral"
            elif input_down:
                new_action = "crouch"
            elif rel_horizontal == -1:
                new_action = "walk_back"
            elif rel_horizontal == 1:
                new_action = "walk_forward"
            else:
                new_action = "idle"

    _apply_action(fighter, prev_action, new_action)

func _current_round_state() -> String:
    var parent = get_parent()
    if parent != null:
        var scene_state = parent.get("round_state")
        if scene_state != null:
            return str(scene_state)
    if sibling_systems.has("round_system"):
        var round_state = sibling_systems["round_system"].get("round_state")
        if round_state != null:
            return str(round_state)
    return "fighting"

func _apply_action(fighter, prev_action: String, new_action: String) -> void:
    fighter.current_action = new_action
    if new_action != prev_action:
        fighter.action_frame = 0
        print("[trace] input.action_change fighter=%s from=%s to=%s" % [fighter.name, prev_action, new_action])
    else:
        fighter.action_frame = int(fighter.action_frame) + 1

func _clear_attack_inputs(fighter) -> void:
    fighter.input_light_punch = false
    fighter.input_medium_punch = false
    fighter.input_heavy_punch = false
    fighter.input_light_kick = false
    fighter.input_medium_kick = false
    fighter.input_heavy_kick = false

func _cpu_action_for_plan(fighter, ai_plan: String, prev_action: String) -> Dictionary:
    var facing_direction: int = int(fighter.facing_direction)
    var special_cooldown: int = int(fighter.special_cooldown_timer)
    var projectile_on_screen: int = int(fighter.projectile_on_screen)
    var action_frame: int = int(fighter.action_frame)
    var is_airborne: bool = bool(fighter.is_airborne)

    if is_airborne and prev_action in ["jump_neutral", "jump_forward", "jump_back"]:
        return {{"action": prev_action}}

    if _is_committed_action(prev_action) and action_frame < _committed_action_frames(prev_action):
        return {{"action": prev_action}}

    match ai_plan:
        "approach":
            return {{"right": facing_direction == 1, "left": facing_direction == -1}}
        "retreat":
            return {{"left": facing_direction == 1, "right": facing_direction == -1}}
        "block":
            if test_mode == "guard_high":
                return {{
                    "action": "block_high",
                }}
            if test_mode == "guard_low":
                return {{
                    "action": "block_low",
                    "down": true,
                }}
            return {{
                "left": facing_direction == 1,
                "right": facing_direction == -1,
                "down": int(Time.get_ticks_msec() / 150) % 2 == 0,
            }}
        "jump":
            return {{"action": "jump_forward" if facing_direction == 1 else "jump_back"}}
        "anti_air":
            return _cpu_attack_action(prev_action, action_frame, "heavy_punch")
        "whiff_punish":
            return _cpu_attack_action(prev_action, action_frame, "medium_kick")
        "attack_far":
            if special_cooldown == 0 and projectile_on_screen == 0:
                return {{"action": "special_projectile"}}
            return {{"right": facing_direction == 1, "left": facing_direction == -1}}
        "attack_close":
            if test_mode == "aggressor":
                return _cpu_attack_action(prev_action, action_frame, "heavy_punch")
            var standing_attacks := ["light_punch", "medium_punch", "heavy_punch", "light_kick", "medium_kick", "heavy_kick"]
            return _cpu_attack_action(prev_action, action_frame, standing_attacks[randi() % standing_attacks.size()])
        _:
            return {{}}

func _cpu_attack_action(prev_action: String, action_frame: int, action_name: String) -> Dictionary:
    if action_name == "":
        return {{}}
    if prev_action == action_name and action_frame >= _committed_action_frames(action_name):
        return {{}}
    return {{"action": action_name}}

func _is_committed_action(action: String) -> bool:
    return {{
        "light_punch": true,
        "medium_punch": true,
        "heavy_punch": true,
        "light_kick": true,
        "medium_kick": true,
        "heavy_kick": true,
        "crouch_light_punch": true,
        "crouch_medium_punch": true,
        "crouch_heavy_punch": true,
        "crouch_light_kick": true,
        "crouch_medium_kick": true,
        "crouch_heavy_kick": true,
        "jump_light_punch": true,
        "jump_medium_punch": true,
        "jump_heavy_punch": true,
        "jump_light_kick": true,
        "jump_medium_kick": true,
        "jump_heavy_kick": true,
        "special_projectile": true,
        "special_uppercut": true,
        "special_spinning": true,
    }}.has(action)

func _committed_action_frames(action: String) -> int:
    if action.begins_with("special_"):
        return 26
    if action.begins_with("jump_"):
        return 14
    if action.begins_with("heavy_") or action.begins_with("crouch_heavy_") or action.begins_with("jump_heavy_"):
        return 14
    if action.begins_with("medium_") or action.begins_with("crouch_medium_") or action.begins_with("jump_medium_"):
        return 12
    return 10

func _should_preserve_action(action: String, action_frame: int, is_airborne: bool) -> bool:
    if action == "":
        return false
    if action in ["jump_neutral", "jump_forward", "jump_back"] and is_airborne:
        return true
    return _is_committed_action(action) and action_frame < _committed_action_frames(action)

func _check_motion(buffer: Array, pattern: Array) -> bool:
    if buffer.size() < pattern.size():
        return false

    var pattern_idx := pattern.size() - 1
    var buffer_idx := buffer.size() - 1
    while buffer_idx >= 0 and pattern_idx >= 0:
        var entry = buffer[buffer_idx] as Dictionary
        var direction = str(entry.get("dir", ""))
        if direction == pattern[pattern_idx]:
            pattern_idx -= 1
        buffer_idx -= 1
    return pattern_idx < 0

func _motion_tail(buffer: Array, limit: int = 8) -> Array:
    var out: Array = []
    var start_index: int = max(buffer.size() - limit, 0)
    for i in range(start_index, buffer.size()):
        var entry = buffer[i] as Dictionary
        out.append(str(entry.get("dir", "")))
    return out
"""
