from __future__ import annotations


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    gravity = _float(constants, "gravity", 0.6)
    pushback_friction = _float(constants, "pushback_friction", 0.5)
    floor_y = _float(constants, "floor_y", 0.0)
    walk_speed_forward = _float(constants, "walk_speed_forward", 4.5)
    walk_speed_back = _float(constants, "walk_speed_back", 3.0)
    stage_left = _float(constants, "stage_left", 100.0)
    stage_right = _float(constants, "stage_right", 1820.0)
    air_friction = _float(constants, "air_friction", 0.98)
    return f"""extends Node
## movement_system - generated by 2d_fighter template python
## Reads:  fighter.current_action, fighter.action_frame, fighter.hitstop_timer, fighter.is_airborne, fighter.position, fighter.pushback_velocity, fighter.velocity, fighter.facing_direction, game.round_state
## Writes: fighter.position, fighter.velocity, fighter.facing_direction, fighter.is_airborne, fighter.pushback_velocity

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _ground_y_by_fighter: Dictionary = {{}}

@export var gravity: float = {gravity}
@export var pushback_friction: float = {pushback_friction}
@export var floor_y: float = {floor_y}
@export var walk_speed_forward: float = {walk_speed_forward}
@export var walk_speed_back: float = {walk_speed_back}
@export var stage_left: float = {stage_left}
@export var stage_right: float = {stage_right}
@export var air_friction: float = {air_friction}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("gravity"): gravity = config["gravity"] as float
    if config.has("pushback_friction"): pushback_friction = config["pushback_friction"] as float
    if config.has("floor_y"): floor_y = config["floor_y"] as float
    if config.has("walk_speed_forward"): walk_speed_forward = config["walk_speed_forward"] as float
    if config.has("walk_speed_back"): walk_speed_back = config["walk_speed_back"] as float
    if config.has("stage_left"): stage_left = config["stage_left"] as float
    if config.has("stage_right"): stage_right = config["stage_right"] as float
    if config.has("air_friction"): air_friction = config["air_friction"] as float
    _ground_y_by_fighter.clear()

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    if fighters.size() < 2:
        return
    var round_state := _current_round_state()
    _update_fighter(fighters[0], fighters[1], round_state)
    _update_fighter(fighters[1], fighters[0], round_state)

func _current_round_state() -> String:
    var parent = get_parent()
    if parent != null:
        var scene_state = parent.get("round_state")
        if scene_state != null:
            return str(scene_state)
    if sibling_systems.has("round_system"):
        var round_state = sibling_systems["round_system"].get("round_state")
        if round_state != null:
            return str(round_state)
    return "fighting"

func _ensure_ground_anchor(fighter) -> float:
    var key := str(fighter.name)
    if not _ground_y_by_fighter.has(key):
        var anchor := float(fighter.position.y)
        if floor_y > 0.0 and absf(floor_y - anchor) < 160.0:
            anchor = floor_y
        _ground_y_by_fighter[key] = anchor
    return float(_ground_y_by_fighter[key])

func _fighter_walk_speed(fighter, forward: bool) -> float:
    var property_name := "walk_speed" if forward else "back_walk_speed"
    var configured = fighter.get(property_name)
    if configured != null and float(configured) > 0.0:
        return float(configured)
    return walk_speed_forward if forward else walk_speed_back

func _jump_velocity_x(fighter) -> float:
    var raw = fighter.get("jump_velocity_x")
    if raw != null and absf(float(raw)) > 0.0:
        return absf(float(raw))
    return 6.0

func _jump_velocity_y(fighter) -> float:
    var raw = fighter.get("jump_velocity_y")
    if raw != null and float(raw) < 0.0:
        return float(raw)
    return -18.0

func _rect_like(value: Variant, fallback: Rect2) -> Rect2:
    if value is Rect2:
        return value as Rect2
    if value is Dictionary:
        var box: Dictionary = value as Dictionary
        if box.has("x") and box.has("y") and box.has("w") and box.has("h"):
            return Rect2(
                float(box.get("x", 0.0)) - (float(box.get("w", 0.0)) * 0.5),
                float(box.get("y", 0.0)) - float(box.get("h", 0.0)),
                float(box.get("w", 0.0)),
                float(box.get("h", 0.0))
            )
    return fallback

func _fighter_half_width(fighter) -> float:
    var fallback := Rect2(-60.0, -180.0, 120.0, 180.0)
    var hurtbox: Rect2 = _rect_like(fighter.get("stand_hurtbox"), fallback)
    if bool(fighter.get("is_crouching")):
        hurtbox = _rect_like(fighter.get("crouch_hurtbox"), hurtbox)
    elif bool(fighter.get("is_airborne")):
        hurtbox = _rect_like(fighter.get("air_hurtbox"), hurtbox)
    if hurtbox is Rect2:
        return max(absf(hurtbox.size.x) * 0.5, 40.0)
    return 60.0

func _fighter_min_gap(fighter, opponent) -> float:
    return _fighter_half_width(fighter) + _fighter_half_width(opponent) - 16.0

func _update_fighter(fighter, opponent, round_state: String) -> void:
    if fighter == null or opponent == null:
        return

    var ground_y := _ensure_ground_anchor(fighter)
    var action := str(fighter.current_action)
    var action_frame := int(fighter.action_frame)
    var velocity: Vector2 = fighter.velocity
    var was_airborne := bool(fighter.is_airborne)
    var facing := 1 if int(fighter.facing_direction) >= 0 else -1

    if int(fighter.hitstop_timer) > 0:
        return

    if not was_airborne:
        if action == "jump_neutral":
            velocity.y = _jump_velocity_y(fighter)
            velocity.x = 0.0
            was_airborne = true
            print("[trace] movement.jump fighter=%s kind=neutral vel=%s" % [fighter.name, str(velocity)])
        elif action == "jump_forward":
            velocity.y = _jump_velocity_y(fighter)
            velocity.x = _jump_velocity_x(fighter) * facing
            was_airborne = true
            print("[trace] movement.jump fighter=%s kind=forward vel=%s" % [fighter.name, str(velocity)])
        elif action == "jump_back":
            velocity.y = _jump_velocity_y(fighter)
            velocity.x = -_jump_velocity_x(fighter) * facing
            was_airborne = true
            print("[trace] movement.jump fighter=%s kind=back vel=%s" % [fighter.name, str(velocity)])
        elif action == "special_uppercut" and action_frame == 0:
            velocity.y = _jump_velocity_y(fighter) * 1.04
            velocity.x = _jump_velocity_x(fighter) * facing * 0.92
            was_airborne = true
            print("[trace] movement.special_start fighter=%s move=shoryuken vel=%s" % [fighter.name, str(velocity)])
        elif action == "special_spinning" and action_frame == 0:
            velocity.x = _fighter_walk_speed(fighter, true) * facing * 1.4
            print("[trace] movement.special_start fighter=%s move=tatsumaki vel=%s" % [fighter.name, str(velocity)])

    if round_state != "fighting" and not was_airborne:
        velocity.x = 0.0

    if was_airborne:
        if action == "special_uppercut":
            velocity.y += gravity * 0.8
            velocity.x = _jump_velocity_x(fighter) * facing * 0.84
        elif action == "special_spinning":
            velocity.y += gravity * 0.28
            velocity.x = _fighter_walk_speed(fighter, true) * facing * 1.55
        else:
            velocity.y += gravity
            velocity.x *= air_friction
    else:
        velocity.y = 0.0
        if action == "walk_forward":
            velocity.x = _fighter_walk_speed(fighter, true) * facing
        elif action == "walk_back":
            velocity.x = -_fighter_walk_speed(fighter, false) * facing
        elif action == "special_spinning":
            velocity.x = _fighter_walk_speed(fighter, true) * facing * 1.4
        else:
            velocity.x = 0.0

    var new_pos: Vector2 = fighter.position + velocity
    var pushback := float(fighter.pushback_velocity)
    if absf(pushback) > 0.001:
        new_pos.x += pushback

    new_pos.x = clampf(new_pos.x, stage_left, stage_right)

    var min_gap := _fighter_min_gap(fighter, opponent)
    if fighter.position.x <= opponent.position.x:
        new_pos.x = minf(new_pos.x, float(opponent.position.x) - min_gap)
    else:
        new_pos.x = maxf(new_pos.x, float(opponent.position.x) + min_gap)

    var is_airborne_now := was_airborne or (new_pos.y < ground_y - 0.5)
    if new_pos.y >= ground_y:
        if was_airborne:
            print("[trace] movement.landed fighter=%s pos=%s" % [fighter.name, str(new_pos)])
        new_pos.y = ground_y
        velocity.y = 0.0
        is_airborne_now = false

    fighter.position = new_pos
    fighter.velocity = velocity
    fighter.is_airborne = is_airborne_now

    var desired_facing := 1 if fighter.position.x < opponent.position.x else -1
    if action not in ["intro", "victory", "ko"] and desired_facing != int(fighter.facing_direction):
        fighter.facing_direction = desired_facing
        print("[trace] movement.facing_change fighter=%s facing=%d" % [fighter.name, desired_facing])

    if pushback > 0.0:
        fighter.pushback_velocity = maxf(0.0, pushback - pushback_friction)
    elif pushback < 0.0:
        fighter.pushback_velocity = minf(0.0, pushback + pushback_friction)
"""
