from __future__ import annotations

from rayxi.build.template_codegen import resolve_constant, resolve_property_name


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    projectile_base_speed = _float(
        constants,
        "projectile_speed",
        float(resolve_constant(constants, ("projectile_base_speed",), 6.0)),
    )
    projectile_max_lifetime_frames = _int(
        constants,
        "projectile_max_lifetime",
        int(resolve_constant(constants, ("projectile_max_lifetime_frames",), 120)),
    )
    projectile_base_damage = _int(
        constants,
        "projectile_base_damage",
        int(resolve_constant(constants, ("projectile_damage",), 60)),
    )
    projectile_powered_speed_multiplier = _float(
        constants,
        "projectile_powered_speed_multiplier",
        float(resolve_constant(constants, ("projectile_damage_multiplier",), 1.5)),
    )
    lifetime_prop = resolve_property_name(
        slice_data,
        "projectile",
        ("lifetime_frames", "max_lifetime_frames"),
        default="lifetime_frames",
    )
    powered_prop = resolve_property_name(
        slice_data,
        "projectile",
        ("is_powered", "is_powered_up"),
        default="is_powered",
    )
    spawn_offset_prop = resolve_property_name(
        slice_data,
        "fighter",
        ("projectile_spawn_offset",),
        default="projectile_spawn_offset",
    )
    return f"""extends Node
## projectile_system - generated by 2d_fighter template python
## Reads:  fighter.facing_direction, fighter.projectile_on_screen, projectile.active, projectile.frames_alive, fighter.position
## Writes: fighter.projectile_on_screen, fighter.is_firing_projectile, projectile.position, projectile.owner_id, projectile.active, projectile.frames_alive, projectile.velocity, projectile.{powered_prop}, projectile.{lifetime_prop}, projectile.speed, projectile.damage

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}

@export var projectile_base_speed: float = {projectile_base_speed}
@export var projectile_max_lifetime_frames: int = {projectile_max_lifetime_frames}
@export var projectile_base_damage: int = {projectile_base_damage}
@export var projectile_powered_speed_multiplier: float = {projectile_powered_speed_multiplier}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("projectile_speed"):
        projectile_base_speed = config["projectile_speed"] as float
    elif config.has("projectile_base_speed"):
        projectile_base_speed = config["projectile_base_speed"] as float
    if config.has("projectile_max_lifetime"):
        projectile_max_lifetime_frames = config["projectile_max_lifetime"] as int
    elif config.has("projectile_max_lifetime_frames"):
        projectile_max_lifetime_frames = config["projectile_max_lifetime_frames"] as int
    if config.has("projectile_base_damage"):
        projectile_base_damage = config["projectile_base_damage"] as int
    if config.has("projectile_powered_speed_multiplier"):
        projectile_powered_speed_multiplier = config["projectile_powered_speed_multiplier"] as float
    elif config.has("projectile_damage_multiplier"):
        projectile_powered_speed_multiplier = config["projectile_damage_multiplier"] as float
    if not entity_pools.has("projectiles"):
        entity_pools["projectiles"] = []

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    _update_projectiles()
    _update_projectile_counts()

func _update_projectiles() -> void:
    var projectiles: Array = entity_pools.get("projectiles", [])
    if projectiles.is_empty():
        return

    var survivors: Array = []
    for proj in projectiles:
        if proj == null:
            continue
        if not is_instance_valid(proj):
            continue
        if not bool(proj.active):
            _retire_projectile(proj, "inactive")
            continue

        proj.frames_alive = int(proj.frames_alive) + 1
        if int(proj.frames_alive) >= int(proj.{lifetime_prop}):
            proj.active = false
            _retire_projectile(proj, "lifetime")
            continue

        proj.position = proj.position + proj.velocity
        proj.visible = true
        survivors.append(proj)
        print("[trace] projectile.step id=%s pos=%s velocity=%s frames_alive=%d" % [
            proj.name,
            str(proj.position),
            str(proj.velocity),
            proj.frames_alive
        ])

    entity_pools["projectiles"] = survivors

func _retire_projectile(proj, reason: String) -> void:
    if proj == null or not is_instance_valid(proj):
        return
    proj.visible = false
    print("[trace] projectile.despawn id=%s reason=%s" % [proj.name, reason])
    if proj.get_parent() != null:
        proj.get_parent().remove_child(proj)
    proj.queue_free()

func _update_projectile_counts() -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    for fighter in fighters:
        fighter.projectile_on_screen = 0

    for proj in entity_pools.get("projectiles", []):
        if proj == null or not is_instance_valid(proj) or not bool(proj.active):
            continue
        for fighter in fighters:
            if str(proj.owner_id) == _fighter_owner_id(fighter):
                fighter.projectile_on_screen = int(fighter.projectile_on_screen) + 1
                break

func _fighter_owner_id(fighter) -> String:
    var fighters: Array = entity_pools.get("fighters", [])
    var idx := fighters.find(fighter)
    if idx >= 0:
        return "P%d" % [idx + 1]
    var lower_name := str(fighter.name).to_lower()
    if lower_name.begins_with("p2"):
        return "P2"
    return "P1"

func spawn_hadouken(fighter, powered: bool = false) -> void:
    if fighter == null:
        return
    var proj_script = load("res://scripts/entities/projectile.gd")
    if proj_script == null:
        print("[trace] projectile.spawn_failed reason=missing_script")
        return

    var proj = proj_script.new()
    var owner_id := _fighter_owner_id(fighter)
    var facing := 1 if int(fighter.facing_direction) >= 0 else -1
    var offset := Vector2(108.0, -154.0)
    var fighter_offset = fighter.get("{spawn_offset_prop}")
    if fighter_offset is Vector2:
        offset = fighter_offset
    elif proj.get("spawn_offset") != null and proj.spawn_offset is Vector2:
        var projectile_offset: Vector2 = proj.spawn_offset
        if projectile_offset.y <= -48.0 or absf(projectile_offset.x) >= 72.0:
            offset = projectile_offset

    proj.name = "hadouken_%s_%d" % [owner_id, Time.get_ticks_msec()]
    proj.owner_id = owner_id
    proj.position = fighter.position + Vector2(offset.x * facing, offset.y)
    proj.frames_alive = 0
    proj.active = true
    proj.speed = projectile_base_speed * (projectile_powered_speed_multiplier if powered else 1.0)
    proj.{lifetime_prop} = projectile_max_lifetime_frames
    proj.{powered_prop} = powered
    proj.damage = projectile_base_damage
    proj.velocity = Vector2(proj.speed * facing, 0.0)
    if proj.get("visual_asset_prefix") != null and fighter.get("visual_asset_prefix") != null:
        proj.visual_asset_prefix = str(fighter.get("visual_asset_prefix"))
    if proj.get("spawn_offset") != null:
        proj.spawn_offset = offset
    if proj.get("hitbox_width") != null:
        proj.hitbox_width = max(int(proj.hitbox_width), 96)
    if proj.get("hitbox_height") != null:
        proj.hitbox_height = max(int(proj.hitbox_height), 56)
    proj.visible = true

    add_child(proj)
    entity_pools["projectiles"].append(proj)
    fighter.is_firing_projectile = false

    var power_label := "powered" if powered else "normal"
    print("[trace] projectile.spawn move=hadouken owner=%s pos=%s direction=%d power=%s damage=%d" % [
        owner_id,
        str(proj.position),
        facing,
        power_label,
        proj.damage
    ])
"""
