from __future__ import annotations

from rayxi.build.template_codegen import resolve_constant


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def _float(constants: dict | None, name: str, default: float) -> str:
    raw = default if constants is None else constants.get(name, default)
    return repr(float(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    max_rage_stacks = _int(constants, "max_rage_stacks", 3)
    rage_fill_threshold = _float(constants, "rage_fill_threshold", 40.0)
    powered_special_damage_multiplier = _float(
        constants,
        "powered_special_damage_multiplier",
        float(resolve_constant(constants, ("rage_damage_multiplier",), 1.5)),
    )
    return f"""extends Node
## rage_meter_system - generated by 2d_fighter template python
## Reads:  fighter.rage_stacks, fighter.rage_fill_value, fighter.is_powered_special
## Writes: fighter.rage_stacks, fighter.rage_fill_value, fighter.is_powered_special

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _pending_damage: Dictionary = {{}}

@export var max_rage_stacks: int = {max_rage_stacks}
@export var rage_fill_threshold: float = {rage_fill_threshold}
@export var powered_special_damage_multiplier: float = {powered_special_damage_multiplier}
@export var test_mode: String = ""

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("max_rage_stacks"):
        max_rage_stacks = config["max_rage_stacks"] as int
    if config.has("rage_fill_threshold"):
        rage_fill_threshold = config["rage_fill_threshold"] as float
    if config.has("powered_special_damage_multiplier"):
        powered_special_damage_multiplier = config["powered_special_damage_multiplier"] as float
    if config.has("test_mode"):
        test_mode = str(config["test_mode"])
    _pending_damage.clear()

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        _apply_pending_damage(fighter)

func _fighter_key(fighter) -> String:
    return str(fighter.get_instance_id())

func process_damage_event(fighter, damage: int) -> void:
    if fighter == null:
        return
    var key := _fighter_key(fighter)
    var total := int(_pending_damage.get(key, 0))
    _pending_damage[key] = total + max(damage, 0)
    print("[trace] rage.damage_event fighter=%s queued_damage=%d" % [
        fighter.name,
        _pending_damage[key],
    ])

func _apply_pending_damage(fighter) -> void:
    var key := _fighter_key(fighter)
    var damage_taken: float = float(_pending_damage.get(key, 0))
    if damage_taken <= 0.0:
        return
    _pending_damage.erase(key)

    var current_stacks: int = int(fighter.get("rage_stacks") if fighter.get("rage_stacks") != null else 0)
    var current_fill: float = float(fighter.get("rage_fill_value") if fighter.get("rage_fill_value") != null else 0.0)
    if current_stacks >= max_rage_stacks:
        fighter.rage_fill_value = 0.0
        return

    var fill_increment: float = damage_taken / max(rage_fill_threshold, 1.0)
    var new_fill: float = current_fill + fill_increment
    while new_fill >= 1.0 and current_stacks < max_rage_stacks:
        current_stacks += 1
        new_fill -= 1.0
        fighter.rage_stacks = current_stacks
        print("[trace] rage.stack_gained fighter=%s new_stacks=%d fill_remaining=%.3f" % [
            fighter.name,
            current_stacks,
            max(new_fill, 0.0),
        ])

    fighter.rage_fill_value = 0.0 if current_stacks >= max_rage_stacks else clampf(new_fill, 0.0, 0.999)
    if current_stacks < max_rage_stacks:
        print("[trace] rage.fill_progress fighter=%s damage=%.1f fill=%.3f" % [
            fighter.name,
            damage_taken,
            fighter.rage_fill_value,
        ])

func consume_stack_for_power_up(fighter) -> bool:
    if fighter == null:
        return false
    var stacks: int = int(fighter.get("rage_stacks") if fighter.get("rage_stacks") != null else 0)
    if stacks <= 0:
        fighter.is_powered_special = false
        return false
    fighter.rage_stacks = stacks - 1
    fighter.is_powered_special = true
    print("[trace] rage.stack_consumed fighter=%s remaining_stacks=%d powered_special=true" % [
        fighter.name,
        fighter.rage_stacks,
    ])
    return true

func clear_powered_special(fighter) -> void:
    if fighter == null:
        return
    if bool(fighter.get("is_powered_special")):
        fighter.is_powered_special = false
        print("[trace] rage.powered_special_cleared fighter=%s reason=move_end" % fighter.name)

func process_round_start() -> void:
    _pending_damage.clear()
    var fighters: Array = entity_pools.get("fighters", [])
    for fighter in fighters:
        if fighter == null:
            continue
        fighter.rage_stacks = 0
        fighter.rage_fill_value = 0.0
        fighter.is_powered_special = false
    if test_mode == "rage_ready" and fighters.size() > 0 and fighters[0] != null:
        fighters[0].rage_stacks = min(1, max_rage_stacks)
        fighters[0].rage_fill_value = 0.0
        print("[trace] rage.test_seed fighter=%s stacks=%d fill=0.0 mode=%s" % [
            fighters[0].name,
            fighters[0].rage_stacks,
            test_mode,
        ])
    for fighter in fighters:
        if fighter == null:
            continue
        print("[trace] rage.round_reset fighter=%s stacks=%d fill=%.3f powered=%s" % [
            fighter.name,
            int(fighter.rage_stacks),
            float(fighter.rage_fill_value),
            str(bool(fighter.is_powered_special)),
        ])
"""
