from __future__ import annotations


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    rounds_to_win = _int(constants, "rounds_to_win", 2)
    round_duration_frames = _int(constants, "round_duration_frames", 5940)
    max_health = _int(constants, "max_health", 1000)
    return f"""extends Node
## round_system - generated by 2d_fighter template python
## Reads:  fighter.current_health, fighter.current_hp, fighter.is_ko, fighter.round_wins, fighter.player_slot
## Writes: fighter.round_wins, game.current_round, game.round_timer_frames, game.round_state, game.round_winner_slot, game.match_winner_slot

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}
var _round_start_positions: Dictionary = {{}}

var round_state: String = "pre_round"
var round_timer_frames: int = {round_duration_frames}
var current_round: int = 1
var round_winner_slot: int = -1
var match_winner_slot: int = -1

@export var rounds_to_win: int = {rounds_to_win}
@export var round_duration_frames: int = {round_duration_frames}
@export var max_health: int = {max_health}
@export var pre_round_frames: int = 60
@export var ko_delay_frames: int = 60
@export var round_over_delay_frames: int = 120

var _state_frame_counter: int = 0

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("rounds_to_win"):
        rounds_to_win = config["rounds_to_win"] as int
    if config.has("round_duration_frames"):
        round_duration_frames = config["round_duration_frames"] as int
    if config.has("max_health"):
        max_health = config["max_health"] as int
    _round_start_positions.clear()
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        _round_start_positions[str(fighter.name)] = fighter.position
        if fighter.get("round_wins") == null:
            fighter.round_wins = 0
    round_state = "pre_round"
    round_timer_frames = round_duration_frames
    current_round = 1
    round_winner_slot = -1
    match_winner_slot = -1
    _state_frame_counter = pre_round_frames
    print("[trace] round.setup rounds_to_win=%d round_duration=%d max_health=%d" % [
        rounds_to_win,
        round_duration_frames,
        max_health,
    ])

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    match round_state:
        "pre_round":
            _process_pre_round()
        "fighting":
            _process_fighting()
        "ko":
            _countdown_to("round_over", ko_delay_frames)
        "time_up":
            _countdown_to("round_over", ko_delay_frames)
        "round_over":
            _process_round_over()
        "match_over":
            pass

func _process_pre_round() -> void:
    if _state_frame_counter == pre_round_frames:
        round_timer_frames = round_duration_frames
        round_winner_slot = -1
        _reset_round_state()
        print("[trace] round.pre_round_start round=%d timer=%d" % [current_round, round_timer_frames])
    _state_frame_counter = max(_state_frame_counter - 1, 0)
    if _state_frame_counter == 0:
        _set_round_state("fighting")

func _process_fighting() -> void:
    round_timer_frames = max(round_timer_frames - 1, 0)
    var fighters: Array = entity_pools.get("fighters", [])
    var p1 = _fighter_by_slot(0, fighters)
    var p2 = _fighter_by_slot(1, fighters)
    if p1 != null and (_is_ko(p1) or _current_health(p1) <= 0):
        round_winner_slot = 1
        print("[trace] round.ko winner_slot=%d loser=%s" % [round_winner_slot, p1.name])
        _set_round_state("ko")
        return
    if p2 != null and (_is_ko(p2) or _current_health(p2) <= 0):
        round_winner_slot = 0
        print("[trace] round.ko winner_slot=%d loser=%s" % [round_winner_slot, p2.name])
        _set_round_state("ko")
        return
    if round_timer_frames <= 0:
        var p1_hp = _current_health(p1)
        var p2_hp = _current_health(p2)
        if p1_hp > p2_hp:
            round_winner_slot = 0
        elif p2_hp > p1_hp:
            round_winner_slot = 1
        else:
            round_winner_slot = -1
        print("[trace] round.time_up winner_slot=%d p1_hp=%d p2_hp=%d" % [round_winner_slot, p1_hp, p2_hp])
        _set_round_state("time_up")

func _process_round_over() -> void:
    if _state_frame_counter == round_over_delay_frames:
        _award_round_win()
        if _determine_match_winner():
            _set_round_state("match_over")
            print("[trace] round.match_over winner_slot=%d" % match_winner_slot)
            return
    _state_frame_counter = max(_state_frame_counter - 1, 0)
    if _state_frame_counter == 0 and match_winner_slot < 0:
        current_round += 1
        _set_round_state("pre_round")

func _countdown_to(next_state: String, duration: int) -> void:
    if _state_frame_counter <= 0:
        _state_frame_counter = duration
    _state_frame_counter = max(_state_frame_counter - 1, 0)
    if _state_frame_counter == 0:
        _set_round_state(next_state)

func _set_round_state(next_state: String) -> void:
    if round_state == next_state:
        return
    print("[trace] round.transition from=%s to=%s" % [round_state, next_state])
    round_state = next_state
    if next_state == "pre_round":
        _state_frame_counter = pre_round_frames
    elif next_state == "ko" or next_state == "time_up":
        _state_frame_counter = ko_delay_frames
    elif next_state == "round_over":
        _state_frame_counter = round_over_delay_frames
    else:
        _state_frame_counter = 0

func _reset_round_state() -> void:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        var key = str(fighter.name)
        if _round_start_positions.has(key):
            fighter.position = _round_start_positions[key]
        fighter.velocity = Vector2.ZERO
        fighter.is_airborne = false
        fighter.pushback_velocity = 0.0
        fighter.current_action = "intro"
        fighter.action_frame = 0
    for system_name in sibling_systems.keys():
        var system = sibling_systems[system_name]
        if system != null and system.has_method("process_round_start"):
            system.process_round_start()
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        print("[trace] round.reset fighter=%s health=%d ko=%s stun=%d rage=%d" % [
            fighter.name,
            _current_health(fighter),
            str(_is_ko(fighter)),
            int(fighter.get("stun_timer") if fighter.get("stun_timer") != null else 0),
            int(fighter.get("rage_stacks") if fighter.get("rage_stacks") != null else 0),
        ])

func _fighter_by_slot(slot: int, fighters: Array):
    for fighter in fighters:
        if fighter != null and int(fighter.get("player_slot") if fighter.get("player_slot") != null else -1) == slot:
            return fighter
    return null

func _current_health(fighter) -> int:
    if fighter == null:
        return 0
    var value = fighter.get("current_health")
    if value == null:
        value = fighter.get("current_hp")
    return int(0 if value == null else value)

func _is_ko(fighter) -> bool:
    if fighter == null:
        return false
    var value = fighter.get("is_ko")
    return bool(value) if value != null else _current_health(fighter) <= 0

func _award_round_win() -> void:
    if round_winner_slot < 0:
        print("[trace] round.draw round=%d" % current_round)
        return
    var winner = _fighter_by_slot(round_winner_slot, entity_pools.get("fighters", []))
    if winner == null:
        return
    winner.round_wins = int(winner.get("round_wins") if winner.get("round_wins") != null else 0) + 1
    print("[trace] round.win_awarded fighter=%s slot=%d total_wins=%d" % [
        winner.name,
        round_winner_slot,
        winner.round_wins,
    ])

func _determine_match_winner() -> bool:
    for fighter in entity_pools.get("fighters", []):
        if fighter == null:
            continue
        if int(fighter.get("round_wins") if fighter.get("round_wins") != null else 0) >= rounds_to_win:
            match_winner_slot = int(fighter.get("player_slot") if fighter.get("player_slot") != null else -1)
            print("[trace] round.match_winner_determined slot=%d wins=%d required=%d" % [
                match_winner_slot,
                fighter.round_wins,
                rounds_to_win,
            ])
            return true
    match_winner_slot = -1
    return false
"""
