from __future__ import annotations


def _int(constants: dict | None, name: str, default: int) -> str:
    raw = default if constants is None else constants.get(name, default)
    return str(int(raw))


def emit_system(slice_data, hlr, spec, constants) -> str:
    max_rage_stacks = _int(constants, "max_rage_stacks", 3)
    hadouken_cooldown = _int(constants, "hadoken_cooldown", 40)
    shoryuken_cooldown = _int(constants, "shoryuken_cooldown", 45)
    tatsumaki_cooldown = _int(constants, "tatsumaki_cooldown", 42)
    return f"""extends Node
## special_move_system - generated by 2d_fighter template python
## Reads:  fighter.special_cooldown_timer, fighter.rage_stacks, fighter.current_action, fighter.action_frame
## Writes: fighter.special_cooldown_timer, fighter.rage_stacks, fighter.is_powered_special

var entity_pools: Dictionary = {{}}
var config: Dictionary = {{}}
var sibling_systems: Dictionary = {{}}

@export var max_rage_stacks: int = {max_rage_stacks}
@export var hadouken_cooldown: int = {hadouken_cooldown}
@export var shoryuken_cooldown: int = {shoryuken_cooldown}
@export var tatsumaki_cooldown: int = {tatsumaki_cooldown}

func setup(pools: Dictionary, cfg: Dictionary = {{}}) -> void:
    entity_pools = pools
    config = cfg
    if config.has("max_rage_stacks"):
        max_rage_stacks = config["max_rage_stacks"] as int
    if config.has("hadoken_cooldown"):
        hadouken_cooldown = config["hadoken_cooldown"] as int
    if config.has("shoryuken_cooldown"):
        shoryuken_cooldown = config["shoryuken_cooldown"] as int
    if config.has("tatsumaki_cooldown"):
        tatsumaki_cooldown = config["tatsumaki_cooldown"] as int

func set_siblings(systems: Dictionary) -> void:
    sibling_systems = systems

func process(_delta: float) -> void:
    var fighters: Array = entity_pools.get("fighters", [])
    for fighter in fighters:
        if fighter == null:
            continue

        var cooldown := int(fighter.special_cooldown_timer)
        if cooldown > 0:
            cooldown = max(cooldown - 1, 0)
            fighter.special_cooldown_timer = cooldown
            if cooldown == 0 and fighter.is_powered_special:
                if sibling_systems.has("rage_meter_system") and sibling_systems["rage_meter_system"].has_method("clear_powered_special"):
                    sibling_systems["rage_meter_system"].clear_powered_special(fighter)
                else:
                    fighter.is_powered_special = false
                print("[trace] special.powered_window_closed fighter=%s" % fighter.name)

        if fighter.hitstop_timer > 0 or fighter.hitstun_timer > 0 or fighter.blockstun_timer > 0:
            continue
        if bool(fighter.is_stunned):
            continue

        var action := str(fighter.current_action)
        if not action.begins_with("special_"):
            continue
        if int(fighter.action_frame) != 0:
            continue
        if int(fighter.special_cooldown_timer) > 0:
            print("[trace] special.cooldown_blocked fighter=%s move=%s remaining=%d" % [fighter.name, action, fighter.special_cooldown_timer])
            continue

        var powered := false
        if sibling_systems.has("rage_meter_system") and sibling_systems["rage_meter_system"].has_method("consume_stack_for_power_up"):
            powered = bool(sibling_systems["rage_meter_system"].consume_stack_for_power_up(fighter))
        elif int(fighter.rage_stacks) > 0:
            fighter.rage_stacks = max(int(fighter.rage_stacks) - 1, 0)
            fighter.is_powered_special = true
            powered = true
        fighter.special_cooldown_timer = max(_cooldown_for_action(fighter, action), 1)
        if not powered:
            fighter.is_powered_special = false

        print("[trace] special.executed fighter=%s move=%s powered=%s cooldown=%d rage=%d" % [
            fighter.name,
            action,
            powered,
            fighter.special_cooldown_timer,
            fighter.rage_stacks
        ])

        if action == "special_projectile":
            print("[trace] special.motion_detected fighter=%s motion=qcf button=punch" % fighter.name)
            if sibling_systems.has("projectile_system") and sibling_systems["projectile_system"].has_method("spawn_hadouken"):
                sibling_systems["projectile_system"].spawn_hadouken(fighter, powered)
        elif action == "special_uppercut":
            print("[trace] special.motion_detected fighter=%s motion=dp button=punch" % fighter.name)
        elif action == "special_spinning":
            print("[trace] special.motion_detected fighter=%s motion=qcb button=kick" % fighter.name)

func _cooldown_for_action(fighter, action: String) -> int:
    match action:
        "special_projectile":
            return int(fighter.get("hadouken_cooldown_frames") if fighter.get("hadouken_cooldown_frames") != null else hadouken_cooldown)
        "special_uppercut":
            return int(fighter.get("shoryuken_cooldown_frames") if fighter.get("shoryuken_cooldown_frames") != null else shoryuken_cooldown)
        "special_spinning":
            return int(fighter.get("tatsumaki_cooldown_frames") if fighter.get("tatsumaki_cooldown_frames") != null else tatsumaki_cooldown)
        _:
            return 1
"""
